###################################################################

# Created by write_sdc on Mon May 13 23:02:28 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_wire_load_mode top
set_wire_load_model -name enG10K -library fsa0m_a_generic_core_ss1p62v125c
set_load -pin_load 0.05 [get_ports CNT_valid]
set_load -pin_load 0.05 [get_ports {CNT[47]}]
set_load -pin_load 0.05 [get_ports {CNT[46]}]
set_load -pin_load 0.05 [get_ports {CNT[45]}]
set_load -pin_load 0.05 [get_ports {CNT[44]}]
set_load -pin_load 0.05 [get_ports {CNT[43]}]
set_load -pin_load 0.05 [get_ports {CNT[42]}]
set_load -pin_load 0.05 [get_ports {CNT[41]}]
set_load -pin_load 0.05 [get_ports {CNT[40]}]
set_load -pin_load 0.05 [get_ports {CNT[39]}]
set_load -pin_load 0.05 [get_ports {CNT[38]}]
set_load -pin_load 0.05 [get_ports {CNT[37]}]
set_load -pin_load 0.05 [get_ports {CNT[36]}]
set_load -pin_load 0.05 [get_ports {CNT[35]}]
set_load -pin_load 0.05 [get_ports {CNT[34]}]
set_load -pin_load 0.05 [get_ports {CNT[33]}]
set_load -pin_load 0.05 [get_ports {CNT[32]}]
set_load -pin_load 0.05 [get_ports {CNT[31]}]
set_load -pin_load 0.05 [get_ports {CNT[30]}]
set_load -pin_load 0.05 [get_ports {CNT[29]}]
set_load -pin_load 0.05 [get_ports {CNT[28]}]
set_load -pin_load 0.05 [get_ports {CNT[27]}]
set_load -pin_load 0.05 [get_ports {CNT[26]}]
set_load -pin_load 0.05 [get_ports {CNT[25]}]
set_load -pin_load 0.05 [get_ports {CNT[24]}]
set_load -pin_load 0.05 [get_ports {CNT[23]}]
set_load -pin_load 0.05 [get_ports {CNT[22]}]
set_load -pin_load 0.05 [get_ports {CNT[21]}]
set_load -pin_load 0.05 [get_ports {CNT[20]}]
set_load -pin_load 0.05 [get_ports {CNT[19]}]
set_load -pin_load 0.05 [get_ports {CNT[18]}]
set_load -pin_load 0.05 [get_ports {CNT[17]}]
set_load -pin_load 0.05 [get_ports {CNT[16]}]
set_load -pin_load 0.05 [get_ports {CNT[15]}]
set_load -pin_load 0.05 [get_ports {CNT[14]}]
set_load -pin_load 0.05 [get_ports {CNT[13]}]
set_load -pin_load 0.05 [get_ports {CNT[12]}]
set_load -pin_load 0.05 [get_ports {CNT[11]}]
set_load -pin_load 0.05 [get_ports {CNT[10]}]
set_load -pin_load 0.05 [get_ports {CNT[9]}]
set_load -pin_load 0.05 [get_ports {CNT[8]}]
set_load -pin_load 0.05 [get_ports {CNT[7]}]
set_load -pin_load 0.05 [get_ports {CNT[6]}]
set_load -pin_load 0.05 [get_ports {CNT[5]}]
set_load -pin_load 0.05 [get_ports {CNT[4]}]
set_load -pin_load 0.05 [get_ports {CNT[3]}]
set_load -pin_load 0.05 [get_ports {CNT[2]}]
set_load -pin_load 0.05 [get_ports {CNT[1]}]
set_load -pin_load 0.05 [get_ports {CNT[0]}]
set_load -pin_load 0.05 [get_ports code_valid]
set_load -pin_load 0.05 [get_ports {HC[47]}]
set_load -pin_load 0.05 [get_ports {HC[46]}]
set_load -pin_load 0.05 [get_ports {HC[45]}]
set_load -pin_load 0.05 [get_ports {HC[44]}]
set_load -pin_load 0.05 [get_ports {HC[43]}]
set_load -pin_load 0.05 [get_ports {HC[42]}]
set_load -pin_load 0.05 [get_ports {HC[41]}]
set_load -pin_load 0.05 [get_ports {HC[40]}]
set_load -pin_load 0.05 [get_ports {HC[39]}]
set_load -pin_load 0.05 [get_ports {HC[38]}]
set_load -pin_load 0.05 [get_ports {HC[37]}]
set_load -pin_load 0.05 [get_ports {HC[36]}]
set_load -pin_load 0.05 [get_ports {HC[35]}]
set_load -pin_load 0.05 [get_ports {HC[34]}]
set_load -pin_load 0.05 [get_ports {HC[33]}]
set_load -pin_load 0.05 [get_ports {HC[32]}]
set_load -pin_load 0.05 [get_ports {HC[31]}]
set_load -pin_load 0.05 [get_ports {HC[30]}]
set_load -pin_load 0.05 [get_ports {HC[29]}]
set_load -pin_load 0.05 [get_ports {HC[28]}]
set_load -pin_load 0.05 [get_ports {HC[27]}]
set_load -pin_load 0.05 [get_ports {HC[26]}]
set_load -pin_load 0.05 [get_ports {HC[25]}]
set_load -pin_load 0.05 [get_ports {HC[24]}]
set_load -pin_load 0.05 [get_ports {HC[23]}]
set_load -pin_load 0.05 [get_ports {HC[22]}]
set_load -pin_load 0.05 [get_ports {HC[21]}]
set_load -pin_load 0.05 [get_ports {HC[20]}]
set_load -pin_load 0.05 [get_ports {HC[19]}]
set_load -pin_load 0.05 [get_ports {HC[18]}]
set_load -pin_load 0.05 [get_ports {HC[17]}]
set_load -pin_load 0.05 [get_ports {HC[16]}]
set_load -pin_load 0.05 [get_ports {HC[15]}]
set_load -pin_load 0.05 [get_ports {HC[14]}]
set_load -pin_load 0.05 [get_ports {HC[13]}]
set_load -pin_load 0.05 [get_ports {HC[12]}]
set_load -pin_load 0.05 [get_ports {HC[11]}]
set_load -pin_load 0.05 [get_ports {HC[10]}]
set_load -pin_load 0.05 [get_ports {HC[9]}]
set_load -pin_load 0.05 [get_ports {HC[8]}]
set_load -pin_load 0.05 [get_ports {HC[7]}]
set_load -pin_load 0.05 [get_ports {HC[6]}]
set_load -pin_load 0.05 [get_ports {HC[5]}]
set_load -pin_load 0.05 [get_ports {HC[4]}]
set_load -pin_load 0.05 [get_ports {HC[3]}]
set_load -pin_load 0.05 [get_ports {HC[2]}]
set_load -pin_load 0.05 [get_ports {HC[1]}]
set_load -pin_load 0.05 [get_ports {HC[0]}]
set_load -pin_load 0.05 [get_ports {M[47]}]
set_load -pin_load 0.05 [get_ports {M[46]}]
set_load -pin_load 0.05 [get_ports {M[45]}]
set_load -pin_load 0.05 [get_ports {M[44]}]
set_load -pin_load 0.05 [get_ports {M[43]}]
set_load -pin_load 0.05 [get_ports {M[42]}]
set_load -pin_load 0.05 [get_ports {M[41]}]
set_load -pin_load 0.05 [get_ports {M[40]}]
set_load -pin_load 0.05 [get_ports {M[39]}]
set_load -pin_load 0.05 [get_ports {M[38]}]
set_load -pin_load 0.05 [get_ports {M[37]}]
set_load -pin_load 0.05 [get_ports {M[36]}]
set_load -pin_load 0.05 [get_ports {M[35]}]
set_load -pin_load 0.05 [get_ports {M[34]}]
set_load -pin_load 0.05 [get_ports {M[33]}]
set_load -pin_load 0.05 [get_ports {M[32]}]
set_load -pin_load 0.05 [get_ports {M[31]}]
set_load -pin_load 0.05 [get_ports {M[30]}]
set_load -pin_load 0.05 [get_ports {M[29]}]
set_load -pin_load 0.05 [get_ports {M[28]}]
set_load -pin_load 0.05 [get_ports {M[27]}]
set_load -pin_load 0.05 [get_ports {M[26]}]
set_load -pin_load 0.05 [get_ports {M[25]}]
set_load -pin_load 0.05 [get_ports {M[24]}]
set_load -pin_load 0.05 [get_ports {M[23]}]
set_load -pin_load 0.05 [get_ports {M[22]}]
set_load -pin_load 0.05 [get_ports {M[21]}]
set_load -pin_load 0.05 [get_ports {M[20]}]
set_load -pin_load 0.05 [get_ports {M[19]}]
set_load -pin_load 0.05 [get_ports {M[18]}]
set_load -pin_load 0.05 [get_ports {M[17]}]
set_load -pin_load 0.05 [get_ports {M[16]}]
set_load -pin_load 0.05 [get_ports {M[15]}]
set_load -pin_load 0.05 [get_ports {M[14]}]
set_load -pin_load 0.05 [get_ports {M[13]}]
set_load -pin_load 0.05 [get_ports {M[12]}]
set_load -pin_load 0.05 [get_ports {M[11]}]
set_load -pin_load 0.05 [get_ports {M[10]}]
set_load -pin_load 0.05 [get_ports {M[9]}]
set_load -pin_load 0.05 [get_ports {M[8]}]
set_load -pin_load 0.05 [get_ports {M[7]}]
set_load -pin_load 0.05 [get_ports {M[6]}]
set_load -pin_load 0.05 [get_ports {M[5]}]
set_load -pin_load 0.05 [get_ports {M[4]}]
set_load -pin_load 0.05 [get_ports {M[3]}]
set_load -pin_load 0.05 [get_ports {M[2]}]
set_load -pin_load 0.05 [get_ports {M[1]}]
set_load -pin_load 0.05 [get_ports {M[0]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[47]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[46]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[45]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[44]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[43]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[42]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[41]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[40]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[39]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[38]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[37]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[36]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[35]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[34]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[33]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[32]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[31]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[30]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[29]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[28]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[27]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[26]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[25]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[24]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[23]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[22]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[21]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[20]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[19]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[18]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[17]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[16]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[15]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[14]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[13]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[12]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[11]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[10]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[9]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[8]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[7]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[6]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[5]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[4]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[3]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[2]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[1]}]
set_load -pin_load 0.05 [get_ports {in_Aid_all[0]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[47]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[46]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[45]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[44]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[43]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[42]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[41]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[40]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[39]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[38]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[37]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[36]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[35]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[34]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[33]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[32]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[31]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[30]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[29]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[28]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[27]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[26]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[25]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[24]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[23]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[22]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[21]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[20]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[19]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[18]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[17]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[16]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[15]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[14]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[13]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[12]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[11]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[10]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[9]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[8]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[7]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[6]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[5]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[4]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[3]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[2]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[1]}]
set_load -pin_load 0.05 [get_ports {in_CNT_all[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports reset]
set_max_capacitance 0.15 [get_ports gray_valid]
set_max_capacitance 0.15 [get_ports {gray_data[7]}]
set_max_capacitance 0.15 [get_ports {gray_data[6]}]
set_max_capacitance 0.15 [get_ports {gray_data[5]}]
set_max_capacitance 0.15 [get_ports {gray_data[4]}]
set_max_capacitance 0.15 [get_ports {gray_data[3]}]
set_max_capacitance 0.15 [get_ports {gray_data[2]}]
set_max_capacitance 0.15 [get_ports {gray_data[1]}]
set_max_capacitance 0.15 [get_ports {gray_data[0]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[47]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[46]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[45]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[44]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[43]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[42]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[41]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[40]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[39]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[38]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[37]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[36]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[35]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[34]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[33]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[32]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[31]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[30]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[29]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[28]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[27]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[26]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[25]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[24]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[23]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[22]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[21]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[20]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[19]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[18]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[17]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[16]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[15]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[14]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[13]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[12]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[11]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[10]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[9]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[8]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[7]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[6]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[5]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[4]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[3]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[2]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[1]}]
set_max_capacitance 0.15 [get_ports {out_Aid_all[0]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[47]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[46]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[45]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[44]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[43]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[42]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[41]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[40]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[39]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[38]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[37]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[36]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[35]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[34]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[33]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[32]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[31]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[30]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[29]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[28]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[27]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[26]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[25]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[24]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[23]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[22]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[21]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[20]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[19]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[18]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[17]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[16]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[15]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[14]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[13]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[12]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[11]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[10]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[9]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[8]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[7]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[6]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[5]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[4]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[3]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[2]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[1]}]
set_max_capacitance 0.15 [get_ports {out_CNT_all[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports reset]
set_max_fanout 10 [get_ports gray_valid]
set_max_fanout 10 [get_ports {gray_data[7]}]
set_max_fanout 10 [get_ports {gray_data[6]}]
set_max_fanout 10 [get_ports {gray_data[5]}]
set_max_fanout 10 [get_ports {gray_data[4]}]
set_max_fanout 10 [get_ports {gray_data[3]}]
set_max_fanout 10 [get_ports {gray_data[2]}]
set_max_fanout 10 [get_ports {gray_data[1]}]
set_max_fanout 10 [get_ports {gray_data[0]}]
set_max_fanout 10 [get_ports {out_Aid_all[47]}]
set_max_fanout 10 [get_ports {out_Aid_all[46]}]
set_max_fanout 10 [get_ports {out_Aid_all[45]}]
set_max_fanout 10 [get_ports {out_Aid_all[44]}]
set_max_fanout 10 [get_ports {out_Aid_all[43]}]
set_max_fanout 10 [get_ports {out_Aid_all[42]}]
set_max_fanout 10 [get_ports {out_Aid_all[41]}]
set_max_fanout 10 [get_ports {out_Aid_all[40]}]
set_max_fanout 10 [get_ports {out_Aid_all[39]}]
set_max_fanout 10 [get_ports {out_Aid_all[38]}]
set_max_fanout 10 [get_ports {out_Aid_all[37]}]
set_max_fanout 10 [get_ports {out_Aid_all[36]}]
set_max_fanout 10 [get_ports {out_Aid_all[35]}]
set_max_fanout 10 [get_ports {out_Aid_all[34]}]
set_max_fanout 10 [get_ports {out_Aid_all[33]}]
set_max_fanout 10 [get_ports {out_Aid_all[32]}]
set_max_fanout 10 [get_ports {out_Aid_all[31]}]
set_max_fanout 10 [get_ports {out_Aid_all[30]}]
set_max_fanout 10 [get_ports {out_Aid_all[29]}]
set_max_fanout 10 [get_ports {out_Aid_all[28]}]
set_max_fanout 10 [get_ports {out_Aid_all[27]}]
set_max_fanout 10 [get_ports {out_Aid_all[26]}]
set_max_fanout 10 [get_ports {out_Aid_all[25]}]
set_max_fanout 10 [get_ports {out_Aid_all[24]}]
set_max_fanout 10 [get_ports {out_Aid_all[23]}]
set_max_fanout 10 [get_ports {out_Aid_all[22]}]
set_max_fanout 10 [get_ports {out_Aid_all[21]}]
set_max_fanout 10 [get_ports {out_Aid_all[20]}]
set_max_fanout 10 [get_ports {out_Aid_all[19]}]
set_max_fanout 10 [get_ports {out_Aid_all[18]}]
set_max_fanout 10 [get_ports {out_Aid_all[17]}]
set_max_fanout 10 [get_ports {out_Aid_all[16]}]
set_max_fanout 10 [get_ports {out_Aid_all[15]}]
set_max_fanout 10 [get_ports {out_Aid_all[14]}]
set_max_fanout 10 [get_ports {out_Aid_all[13]}]
set_max_fanout 10 [get_ports {out_Aid_all[12]}]
set_max_fanout 10 [get_ports {out_Aid_all[11]}]
set_max_fanout 10 [get_ports {out_Aid_all[10]}]
set_max_fanout 10 [get_ports {out_Aid_all[9]}]
set_max_fanout 10 [get_ports {out_Aid_all[8]}]
set_max_fanout 10 [get_ports {out_Aid_all[7]}]
set_max_fanout 10 [get_ports {out_Aid_all[6]}]
set_max_fanout 10 [get_ports {out_Aid_all[5]}]
set_max_fanout 10 [get_ports {out_Aid_all[4]}]
set_max_fanout 10 [get_ports {out_Aid_all[3]}]
set_max_fanout 10 [get_ports {out_Aid_all[2]}]
set_max_fanout 10 [get_ports {out_Aid_all[1]}]
set_max_fanout 10 [get_ports {out_Aid_all[0]}]
set_max_fanout 10 [get_ports {out_CNT_all[47]}]
set_max_fanout 10 [get_ports {out_CNT_all[46]}]
set_max_fanout 10 [get_ports {out_CNT_all[45]}]
set_max_fanout 10 [get_ports {out_CNT_all[44]}]
set_max_fanout 10 [get_ports {out_CNT_all[43]}]
set_max_fanout 10 [get_ports {out_CNT_all[42]}]
set_max_fanout 10 [get_ports {out_CNT_all[41]}]
set_max_fanout 10 [get_ports {out_CNT_all[40]}]
set_max_fanout 10 [get_ports {out_CNT_all[39]}]
set_max_fanout 10 [get_ports {out_CNT_all[38]}]
set_max_fanout 10 [get_ports {out_CNT_all[37]}]
set_max_fanout 10 [get_ports {out_CNT_all[36]}]
set_max_fanout 10 [get_ports {out_CNT_all[35]}]
set_max_fanout 10 [get_ports {out_CNT_all[34]}]
set_max_fanout 10 [get_ports {out_CNT_all[33]}]
set_max_fanout 10 [get_ports {out_CNT_all[32]}]
set_max_fanout 10 [get_ports {out_CNT_all[31]}]
set_max_fanout 10 [get_ports {out_CNT_all[30]}]
set_max_fanout 10 [get_ports {out_CNT_all[29]}]
set_max_fanout 10 [get_ports {out_CNT_all[28]}]
set_max_fanout 10 [get_ports {out_CNT_all[27]}]
set_max_fanout 10 [get_ports {out_CNT_all[26]}]
set_max_fanout 10 [get_ports {out_CNT_all[25]}]
set_max_fanout 10 [get_ports {out_CNT_all[24]}]
set_max_fanout 10 [get_ports {out_CNT_all[23]}]
set_max_fanout 10 [get_ports {out_CNT_all[22]}]
set_max_fanout 10 [get_ports {out_CNT_all[21]}]
set_max_fanout 10 [get_ports {out_CNT_all[20]}]
set_max_fanout 10 [get_ports {out_CNT_all[19]}]
set_max_fanout 10 [get_ports {out_CNT_all[18]}]
set_max_fanout 10 [get_ports {out_CNT_all[17]}]
set_max_fanout 10 [get_ports {out_CNT_all[16]}]
set_max_fanout 10 [get_ports {out_CNT_all[15]}]
set_max_fanout 10 [get_ports {out_CNT_all[14]}]
set_max_fanout 10 [get_ports {out_CNT_all[13]}]
set_max_fanout 10 [get_ports {out_CNT_all[12]}]
set_max_fanout 10 [get_ports {out_CNT_all[11]}]
set_max_fanout 10 [get_ports {out_CNT_all[10]}]
set_max_fanout 10 [get_ports {out_CNT_all[9]}]
set_max_fanout 10 [get_ports {out_CNT_all[8]}]
set_max_fanout 10 [get_ports {out_CNT_all[7]}]
set_max_fanout 10 [get_ports {out_CNT_all[6]}]
set_max_fanout 10 [get_ports {out_CNT_all[5]}]
set_max_fanout 10 [get_ports {out_CNT_all[4]}]
set_max_fanout 10 [get_ports {out_CNT_all[3]}]
set_max_fanout 10 [get_ports {out_CNT_all[2]}]
set_max_fanout 10 [get_ports {out_CNT_all[1]}]
set_max_fanout 10 [get_ports {out_CNT_all[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports reset]
set_max_transition 3 [get_ports gray_valid]
set_max_transition 3 [get_ports {gray_data[7]}]
set_max_transition 3 [get_ports {gray_data[6]}]
set_max_transition 3 [get_ports {gray_data[5]}]
set_max_transition 3 [get_ports {gray_data[4]}]
set_max_transition 3 [get_ports {gray_data[3]}]
set_max_transition 3 [get_ports {gray_data[2]}]
set_max_transition 3 [get_ports {gray_data[1]}]
set_max_transition 3 [get_ports {gray_data[0]}]
set_max_transition 3 [get_ports {out_Aid_all[47]}]
set_max_transition 3 [get_ports {out_Aid_all[46]}]
set_max_transition 3 [get_ports {out_Aid_all[45]}]
set_max_transition 3 [get_ports {out_Aid_all[44]}]
set_max_transition 3 [get_ports {out_Aid_all[43]}]
set_max_transition 3 [get_ports {out_Aid_all[42]}]
set_max_transition 3 [get_ports {out_Aid_all[41]}]
set_max_transition 3 [get_ports {out_Aid_all[40]}]
set_max_transition 3 [get_ports {out_Aid_all[39]}]
set_max_transition 3 [get_ports {out_Aid_all[38]}]
set_max_transition 3 [get_ports {out_Aid_all[37]}]
set_max_transition 3 [get_ports {out_Aid_all[36]}]
set_max_transition 3 [get_ports {out_Aid_all[35]}]
set_max_transition 3 [get_ports {out_Aid_all[34]}]
set_max_transition 3 [get_ports {out_Aid_all[33]}]
set_max_transition 3 [get_ports {out_Aid_all[32]}]
set_max_transition 3 [get_ports {out_Aid_all[31]}]
set_max_transition 3 [get_ports {out_Aid_all[30]}]
set_max_transition 3 [get_ports {out_Aid_all[29]}]
set_max_transition 3 [get_ports {out_Aid_all[28]}]
set_max_transition 3 [get_ports {out_Aid_all[27]}]
set_max_transition 3 [get_ports {out_Aid_all[26]}]
set_max_transition 3 [get_ports {out_Aid_all[25]}]
set_max_transition 3 [get_ports {out_Aid_all[24]}]
set_max_transition 3 [get_ports {out_Aid_all[23]}]
set_max_transition 3 [get_ports {out_Aid_all[22]}]
set_max_transition 3 [get_ports {out_Aid_all[21]}]
set_max_transition 3 [get_ports {out_Aid_all[20]}]
set_max_transition 3 [get_ports {out_Aid_all[19]}]
set_max_transition 3 [get_ports {out_Aid_all[18]}]
set_max_transition 3 [get_ports {out_Aid_all[17]}]
set_max_transition 3 [get_ports {out_Aid_all[16]}]
set_max_transition 3 [get_ports {out_Aid_all[15]}]
set_max_transition 3 [get_ports {out_Aid_all[14]}]
set_max_transition 3 [get_ports {out_Aid_all[13]}]
set_max_transition 3 [get_ports {out_Aid_all[12]}]
set_max_transition 3 [get_ports {out_Aid_all[11]}]
set_max_transition 3 [get_ports {out_Aid_all[10]}]
set_max_transition 3 [get_ports {out_Aid_all[9]}]
set_max_transition 3 [get_ports {out_Aid_all[8]}]
set_max_transition 3 [get_ports {out_Aid_all[7]}]
set_max_transition 3 [get_ports {out_Aid_all[6]}]
set_max_transition 3 [get_ports {out_Aid_all[5]}]
set_max_transition 3 [get_ports {out_Aid_all[4]}]
set_max_transition 3 [get_ports {out_Aid_all[3]}]
set_max_transition 3 [get_ports {out_Aid_all[2]}]
set_max_transition 3 [get_ports {out_Aid_all[1]}]
set_max_transition 3 [get_ports {out_Aid_all[0]}]
set_max_transition 3 [get_ports {out_CNT_all[47]}]
set_max_transition 3 [get_ports {out_CNT_all[46]}]
set_max_transition 3 [get_ports {out_CNT_all[45]}]
set_max_transition 3 [get_ports {out_CNT_all[44]}]
set_max_transition 3 [get_ports {out_CNT_all[43]}]
set_max_transition 3 [get_ports {out_CNT_all[42]}]
set_max_transition 3 [get_ports {out_CNT_all[41]}]
set_max_transition 3 [get_ports {out_CNT_all[40]}]
set_max_transition 3 [get_ports {out_CNT_all[39]}]
set_max_transition 3 [get_ports {out_CNT_all[38]}]
set_max_transition 3 [get_ports {out_CNT_all[37]}]
set_max_transition 3 [get_ports {out_CNT_all[36]}]
set_max_transition 3 [get_ports {out_CNT_all[35]}]
set_max_transition 3 [get_ports {out_CNT_all[34]}]
set_max_transition 3 [get_ports {out_CNT_all[33]}]
set_max_transition 3 [get_ports {out_CNT_all[32]}]
set_max_transition 3 [get_ports {out_CNT_all[31]}]
set_max_transition 3 [get_ports {out_CNT_all[30]}]
set_max_transition 3 [get_ports {out_CNT_all[29]}]
set_max_transition 3 [get_ports {out_CNT_all[28]}]
set_max_transition 3 [get_ports {out_CNT_all[27]}]
set_max_transition 3 [get_ports {out_CNT_all[26]}]
set_max_transition 3 [get_ports {out_CNT_all[25]}]
set_max_transition 3 [get_ports {out_CNT_all[24]}]
set_max_transition 3 [get_ports {out_CNT_all[23]}]
set_max_transition 3 [get_ports {out_CNT_all[22]}]
set_max_transition 3 [get_ports {out_CNT_all[21]}]
set_max_transition 3 [get_ports {out_CNT_all[20]}]
set_max_transition 3 [get_ports {out_CNT_all[19]}]
set_max_transition 3 [get_ports {out_CNT_all[18]}]
set_max_transition 3 [get_ports {out_CNT_all[17]}]
set_max_transition 3 [get_ports {out_CNT_all[16]}]
set_max_transition 3 [get_ports {out_CNT_all[15]}]
set_max_transition 3 [get_ports {out_CNT_all[14]}]
set_max_transition 3 [get_ports {out_CNT_all[13]}]
set_max_transition 3 [get_ports {out_CNT_all[12]}]
set_max_transition 3 [get_ports {out_CNT_all[11]}]
set_max_transition 3 [get_ports {out_CNT_all[10]}]
set_max_transition 3 [get_ports {out_CNT_all[9]}]
set_max_transition 3 [get_ports {out_CNT_all[8]}]
set_max_transition 3 [get_ports {out_CNT_all[7]}]
set_max_transition 3 [get_ports {out_CNT_all[6]}]
set_max_transition 3 [get_ports {out_CNT_all[5]}]
set_max_transition 3 [get_ports {out_CNT_all[4]}]
set_max_transition 3 [get_ports {out_CNT_all[3]}]
set_max_transition 3 [get_ports {out_CNT_all[2]}]
set_max_transition 3 [get_ports {out_CNT_all[1]}]
set_max_transition 3 [get_ports {out_CNT_all[0]}]
create_clock [get_ports clk]  -period 20  -waveform {0 10}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports reset]
set_input_delay -clock clk  -max 10  [get_ports gray_valid]
set_input_delay -clock clk  -min 0  [get_ports gray_valid]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[7]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[7]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[6]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[6]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[5]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[5]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[4]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[4]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[3]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[3]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[2]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[2]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[1]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[1]}]
set_input_delay -clock clk  -max 10  [get_ports {gray_data[0]}]
set_input_delay -clock clk  -min 0  [get_ports {gray_data[0]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[47]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[47]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[46]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[46]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[45]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[45]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[44]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[44]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[43]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[43]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[42]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[42]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[41]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[41]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[40]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[40]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[39]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[39]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[38]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[38]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[37]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[37]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[36]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[36]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[35]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[35]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[34]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[34]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[33]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[33]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[32]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[32]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[31]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[31]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[30]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[30]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[29]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[29]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[28]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[28]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[27]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[27]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[26]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[26]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[25]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[25]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[24]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[24]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[23]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[23]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[22]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[22]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[21]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[21]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[20]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[20]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[19]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[19]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[18]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[18]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[17]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[17]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[16]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[16]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[15]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[15]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[14]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[14]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[13]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[13]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[12]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[12]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[11]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[11]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[10]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[10]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[9]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[9]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[8]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[8]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[7]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[7]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[6]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[6]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[5]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[5]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[4]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[4]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[3]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[3]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[2]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[2]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[1]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[1]}]
set_input_delay -clock clk  -max 10  [get_ports {out_Aid_all[0]}]
set_input_delay -clock clk  -min 0  [get_ports {out_Aid_all[0]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[47]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[47]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[46]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[46]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[45]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[45]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[44]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[44]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[43]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[43]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[42]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[42]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[41]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[41]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[40]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[40]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[39]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[39]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[38]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[38]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[37]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[37]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[36]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[36]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[35]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[35]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[34]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[34]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[33]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[33]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[32]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[32]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[31]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[31]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[30]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[30]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[29]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[29]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[28]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[28]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[27]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[27]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[26]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[26]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[25]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[25]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[24]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[24]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[23]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[23]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[22]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[22]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[21]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[21]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[20]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[20]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[19]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[19]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[18]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[18]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[17]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[17]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[16]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[16]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[15]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[15]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[14]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[14]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[13]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[13]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[12]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[12]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[11]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[11]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[10]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[10]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[9]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[9]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[8]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[8]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[7]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[7]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[6]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[6]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[5]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[5]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[4]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[4]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[3]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[3]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[2]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[2]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[1]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[1]}]
set_input_delay -clock clk  -max 10  [get_ports {out_CNT_all[0]}]
set_input_delay -clock clk  -min 0  [get_ports {out_CNT_all[0]}]
set_output_delay -clock clk  -max 10  [get_ports CNT_valid]
set_output_delay -clock clk  -min 0  [get_ports CNT_valid]
set_output_delay -clock clk  -max 10  [get_ports {CNT[47]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[47]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[46]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[46]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[45]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[45]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[44]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[44]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[43]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[43]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[42]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[42]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[41]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[41]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[40]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[40]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[39]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[39]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[38]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[38]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[37]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[37]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[36]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[36]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[35]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[35]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[34]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[34]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[33]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[33]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[32]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[32]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[31]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[31]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[30]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[30]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[29]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[29]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[28]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[28]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[27]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[27]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[26]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[26]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[25]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[25]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[24]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[24]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[23]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[23]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[22]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[22]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[21]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[21]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[20]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[20]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[19]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[19]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[18]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[18]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[17]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[17]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[16]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[16]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[15]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[15]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[14]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[14]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[13]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[13]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[12]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[12]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[11]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[11]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[10]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[10]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[9]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[9]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[8]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[8]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[7]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[7]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[6]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[6]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[5]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[5]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[4]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[4]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[3]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[3]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[2]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[2]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[1]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[1]}]
set_output_delay -clock clk  -max 10  [get_ports {CNT[0]}]
set_output_delay -clock clk  -min 0  [get_ports {CNT[0]}]
set_output_delay -clock clk  -max 10  [get_ports code_valid]
set_output_delay -clock clk  -min 0  [get_ports code_valid]
set_output_delay -clock clk  -max 10  [get_ports {HC[47]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[47]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[46]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[46]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[45]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[45]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[44]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[44]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[43]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[43]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[42]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[42]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[41]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[41]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[40]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[40]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[39]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[39]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[38]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[38]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[37]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[37]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[36]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[36]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[35]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[35]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[34]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[34]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[33]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[33]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[32]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[32]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[31]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[31]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[30]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[30]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[29]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[29]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[28]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[28]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[27]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[27]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[26]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[26]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[25]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[25]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[24]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[24]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[23]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[23]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[22]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[22]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[21]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[21]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[20]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[20]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[19]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[19]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[18]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[18]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[17]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[17]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[16]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[16]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[15]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[15]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[14]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[14]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[13]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[13]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[12]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[12]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[11]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[11]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[10]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[10]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[9]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[9]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[8]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[8]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[7]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[7]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[6]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[6]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[5]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[5]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[4]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[4]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[3]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[3]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[2]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[2]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[1]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[1]}]
set_output_delay -clock clk  -max 10  [get_ports {HC[0]}]
set_output_delay -clock clk  -min 0  [get_ports {HC[0]}]
set_output_delay -clock clk  -max 10  [get_ports {M[47]}]
set_output_delay -clock clk  -min 0  [get_ports {M[47]}]
set_output_delay -clock clk  -max 10  [get_ports {M[46]}]
set_output_delay -clock clk  -min 0  [get_ports {M[46]}]
set_output_delay -clock clk  -max 10  [get_ports {M[45]}]
set_output_delay -clock clk  -min 0  [get_ports {M[45]}]
set_output_delay -clock clk  -max 10  [get_ports {M[44]}]
set_output_delay -clock clk  -min 0  [get_ports {M[44]}]
set_output_delay -clock clk  -max 10  [get_ports {M[43]}]
set_output_delay -clock clk  -min 0  [get_ports {M[43]}]
set_output_delay -clock clk  -max 10  [get_ports {M[42]}]
set_output_delay -clock clk  -min 0  [get_ports {M[42]}]
set_output_delay -clock clk  -max 10  [get_ports {M[41]}]
set_output_delay -clock clk  -min 0  [get_ports {M[41]}]
set_output_delay -clock clk  -max 10  [get_ports {M[40]}]
set_output_delay -clock clk  -min 0  [get_ports {M[40]}]
set_output_delay -clock clk  -max 10  [get_ports {M[39]}]
set_output_delay -clock clk  -min 0  [get_ports {M[39]}]
set_output_delay -clock clk  -max 10  [get_ports {M[38]}]
set_output_delay -clock clk  -min 0  [get_ports {M[38]}]
set_output_delay -clock clk  -max 10  [get_ports {M[37]}]
set_output_delay -clock clk  -min 0  [get_ports {M[37]}]
set_output_delay -clock clk  -max 10  [get_ports {M[36]}]
set_output_delay -clock clk  -min 0  [get_ports {M[36]}]
set_output_delay -clock clk  -max 10  [get_ports {M[35]}]
set_output_delay -clock clk  -min 0  [get_ports {M[35]}]
set_output_delay -clock clk  -max 10  [get_ports {M[34]}]
set_output_delay -clock clk  -min 0  [get_ports {M[34]}]
set_output_delay -clock clk  -max 10  [get_ports {M[33]}]
set_output_delay -clock clk  -min 0  [get_ports {M[33]}]
set_output_delay -clock clk  -max 10  [get_ports {M[32]}]
set_output_delay -clock clk  -min 0  [get_ports {M[32]}]
set_output_delay -clock clk  -max 10  [get_ports {M[31]}]
set_output_delay -clock clk  -min 0  [get_ports {M[31]}]
set_output_delay -clock clk  -max 10  [get_ports {M[30]}]
set_output_delay -clock clk  -min 0  [get_ports {M[30]}]
set_output_delay -clock clk  -max 10  [get_ports {M[29]}]
set_output_delay -clock clk  -min 0  [get_ports {M[29]}]
set_output_delay -clock clk  -max 10  [get_ports {M[28]}]
set_output_delay -clock clk  -min 0  [get_ports {M[28]}]
set_output_delay -clock clk  -max 10  [get_ports {M[27]}]
set_output_delay -clock clk  -min 0  [get_ports {M[27]}]
set_output_delay -clock clk  -max 10  [get_ports {M[26]}]
set_output_delay -clock clk  -min 0  [get_ports {M[26]}]
set_output_delay -clock clk  -max 10  [get_ports {M[25]}]
set_output_delay -clock clk  -min 0  [get_ports {M[25]}]
set_output_delay -clock clk  -max 10  [get_ports {M[24]}]
set_output_delay -clock clk  -min 0  [get_ports {M[24]}]
set_output_delay -clock clk  -max 10  [get_ports {M[23]}]
set_output_delay -clock clk  -min 0  [get_ports {M[23]}]
set_output_delay -clock clk  -max 10  [get_ports {M[22]}]
set_output_delay -clock clk  -min 0  [get_ports {M[22]}]
set_output_delay -clock clk  -max 10  [get_ports {M[21]}]
set_output_delay -clock clk  -min 0  [get_ports {M[21]}]
set_output_delay -clock clk  -max 10  [get_ports {M[20]}]
set_output_delay -clock clk  -min 0  [get_ports {M[20]}]
set_output_delay -clock clk  -max 10  [get_ports {M[19]}]
set_output_delay -clock clk  -min 0  [get_ports {M[19]}]
set_output_delay -clock clk  -max 10  [get_ports {M[18]}]
set_output_delay -clock clk  -min 0  [get_ports {M[18]}]
set_output_delay -clock clk  -max 10  [get_ports {M[17]}]
set_output_delay -clock clk  -min 0  [get_ports {M[17]}]
set_output_delay -clock clk  -max 10  [get_ports {M[16]}]
set_output_delay -clock clk  -min 0  [get_ports {M[16]}]
set_output_delay -clock clk  -max 10  [get_ports {M[15]}]
set_output_delay -clock clk  -min 0  [get_ports {M[15]}]
set_output_delay -clock clk  -max 10  [get_ports {M[14]}]
set_output_delay -clock clk  -min 0  [get_ports {M[14]}]
set_output_delay -clock clk  -max 10  [get_ports {M[13]}]
set_output_delay -clock clk  -min 0  [get_ports {M[13]}]
set_output_delay -clock clk  -max 10  [get_ports {M[12]}]
set_output_delay -clock clk  -min 0  [get_ports {M[12]}]
set_output_delay -clock clk  -max 10  [get_ports {M[11]}]
set_output_delay -clock clk  -min 0  [get_ports {M[11]}]
set_output_delay -clock clk  -max 10  [get_ports {M[10]}]
set_output_delay -clock clk  -min 0  [get_ports {M[10]}]
set_output_delay -clock clk  -max 10  [get_ports {M[9]}]
set_output_delay -clock clk  -min 0  [get_ports {M[9]}]
set_output_delay -clock clk  -max 10  [get_ports {M[8]}]
set_output_delay -clock clk  -min 0  [get_ports {M[8]}]
set_output_delay -clock clk  -max 10  [get_ports {M[7]}]
set_output_delay -clock clk  -min 0  [get_ports {M[7]}]
set_output_delay -clock clk  -max 10  [get_ports {M[6]}]
set_output_delay -clock clk  -min 0  [get_ports {M[6]}]
set_output_delay -clock clk  -max 10  [get_ports {M[5]}]
set_output_delay -clock clk  -min 0  [get_ports {M[5]}]
set_output_delay -clock clk  -max 10  [get_ports {M[4]}]
set_output_delay -clock clk  -min 0  [get_ports {M[4]}]
set_output_delay -clock clk  -max 10  [get_ports {M[3]}]
set_output_delay -clock clk  -min 0  [get_ports {M[3]}]
set_output_delay -clock clk  -max 10  [get_ports {M[2]}]
set_output_delay -clock clk  -min 0  [get_ports {M[2]}]
set_output_delay -clock clk  -max 10  [get_ports {M[1]}]
set_output_delay -clock clk  -min 0  [get_ports {M[1]}]
set_output_delay -clock clk  -max 10  [get_ports {M[0]}]
set_output_delay -clock clk  -min 0  [get_ports {M[0]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[47]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[47]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[46]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[46]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[45]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[45]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[44]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[44]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[43]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[43]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[42]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[42]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[41]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[41]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[40]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[40]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[39]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[39]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[38]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[38]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[37]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[37]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[36]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[36]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[35]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[35]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[34]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[34]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[33]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[33]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[32]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[32]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[31]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[31]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[30]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[30]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[29]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[29]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[28]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[28]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[27]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[27]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[26]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[26]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[25]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[25]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[24]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[24]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[23]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[23]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[22]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[22]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[21]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[21]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[20]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[20]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[19]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[19]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[18]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[18]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[17]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[17]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[16]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[16]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[15]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[15]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[14]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[14]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[13]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[13]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[12]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[12]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[11]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[11]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[10]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[10]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[9]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[9]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[8]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[8]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[7]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[7]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[6]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[6]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[5]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[5]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[4]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[4]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[3]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[3]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[2]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[2]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[1]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[1]}]
set_output_delay -clock clk  -max 10  [get_ports {in_Aid_all[0]}]
set_output_delay -clock clk  -min 0  [get_ports {in_Aid_all[0]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[47]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[47]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[46]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[46]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[45]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[45]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[44]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[44]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[43]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[43]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[42]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[42]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[41]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[41]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[40]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[40]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[39]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[39]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[38]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[38]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[37]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[37]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[36]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[36]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[35]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[35]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[34]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[34]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[33]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[33]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[32]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[32]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[31]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[31]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[30]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[30]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[29]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[29]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[28]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[28]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[27]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[27]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[26]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[26]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[25]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[25]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[24]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[24]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[23]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[23]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[22]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[22]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[21]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[21]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[20]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[20]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[19]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[19]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[18]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[18]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[17]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[17]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[16]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[16]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[15]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[15]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[14]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[14]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[13]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[13]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[12]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[12]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[11]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[11]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[10]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[10]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[9]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[9]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[8]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[8]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[7]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[7]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[6]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[6]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[5]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[5]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[4]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[4]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[3]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[3]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[2]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[2]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[1]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[1]}]
set_output_delay -clock clk  -max 10  [get_ports {in_CNT_all[0]}]
set_output_delay -clock clk  -min 0  [get_ports {in_CNT_all[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports reset]
set_input_transition -min 0.5  [get_ports reset]
set_input_transition -max 0.5  [get_ports gray_valid]
set_input_transition -min 0.5  [get_ports gray_valid]
set_input_transition -max 0.5  [get_ports {gray_data[7]}]
set_input_transition -min 0.5  [get_ports {gray_data[7]}]
set_input_transition -max 0.5  [get_ports {gray_data[6]}]
set_input_transition -min 0.5  [get_ports {gray_data[6]}]
set_input_transition -max 0.5  [get_ports {gray_data[5]}]
set_input_transition -min 0.5  [get_ports {gray_data[5]}]
set_input_transition -max 0.5  [get_ports {gray_data[4]}]
set_input_transition -min 0.5  [get_ports {gray_data[4]}]
set_input_transition -max 0.5  [get_ports {gray_data[3]}]
set_input_transition -min 0.5  [get_ports {gray_data[3]}]
set_input_transition -max 0.5  [get_ports {gray_data[2]}]
set_input_transition -min 0.5  [get_ports {gray_data[2]}]
set_input_transition -max 0.5  [get_ports {gray_data[1]}]
set_input_transition -min 0.5  [get_ports {gray_data[1]}]
set_input_transition -max 0.5  [get_ports {gray_data[0]}]
set_input_transition -min 0.5  [get_ports {gray_data[0]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[47]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[47]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[46]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[46]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[45]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[45]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[44]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[44]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[43]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[43]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[42]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[42]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[41]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[41]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[40]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[40]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[39]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[39]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[38]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[38]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[37]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[37]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[36]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[36]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[35]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[35]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[34]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[34]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[33]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[33]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[32]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[32]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[31]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[31]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[30]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[30]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[29]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[29]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[28]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[28]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[27]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[27]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[26]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[26]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[25]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[25]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[24]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[24]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[23]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[23]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[22]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[22]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[21]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[21]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[20]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[20]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[19]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[19]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[18]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[18]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[17]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[17]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[16]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[16]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[15]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[15]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[14]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[14]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[13]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[13]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[12]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[12]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[11]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[11]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[10]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[10]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[9]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[9]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[8]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[8]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[7]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[7]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[6]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[6]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[5]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[5]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[4]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[4]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[3]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[3]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[2]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[2]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[1]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[1]}]
set_input_transition -max 0.5  [get_ports {out_Aid_all[0]}]
set_input_transition -min 0.5  [get_ports {out_Aid_all[0]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[47]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[47]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[46]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[46]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[45]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[45]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[44]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[44]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[43]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[43]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[42]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[42]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[41]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[41]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[40]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[40]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[39]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[39]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[38]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[38]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[37]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[37]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[36]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[36]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[35]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[35]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[34]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[34]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[33]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[33]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[32]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[32]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[31]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[31]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[30]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[30]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[29]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[29]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[28]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[28]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[27]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[27]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[26]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[26]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[25]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[25]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[24]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[24]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[23]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[23]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[22]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[22]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[21]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[21]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[20]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[20]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[19]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[19]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[18]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[18]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[17]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[17]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[16]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[16]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[15]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[15]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[14]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[14]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[13]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[13]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[12]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[12]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[11]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[11]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[10]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[10]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[9]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[9]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[8]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[8]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[7]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[7]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[6]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[6]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[5]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[5]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[4]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[4]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[3]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[3]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[2]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[2]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[1]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[1]}]
set_input_transition -max 0.5  [get_ports {out_CNT_all[0]}]
set_input_transition -min 0.5  [get_ports {out_CNT_all[0]}]
