###################################################################

# Created by write_sdc on Fri May 17 20:47:40 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_wire_load_mode top
set_wire_load_model -name enG50K -library fsa0m_a_generic_core_ss1p62v125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {out[95]}]
set_load -pin_load 0.05 [get_ports {out[94]}]
set_load -pin_load 0.05 [get_ports {out[93]}]
set_load -pin_load 0.05 [get_ports {out[92]}]
set_load -pin_load 0.05 [get_ports {out[91]}]
set_load -pin_load 0.05 [get_ports {out[90]}]
set_load -pin_load 0.05 [get_ports {out[89]}]
set_load -pin_load 0.05 [get_ports {out[88]}]
set_load -pin_load 0.05 [get_ports {out[87]}]
set_load -pin_load 0.05 [get_ports {out[86]}]
set_load -pin_load 0.05 [get_ports {out[85]}]
set_load -pin_load 0.05 [get_ports {out[84]}]
set_load -pin_load 0.05 [get_ports {out[83]}]
set_load -pin_load 0.05 [get_ports {out[82]}]
set_load -pin_load 0.05 [get_ports {out[81]}]
set_load -pin_load 0.05 [get_ports {out[80]}]
set_load -pin_load 0.05 [get_ports {out[79]}]
set_load -pin_load 0.05 [get_ports {out[78]}]
set_load -pin_load 0.05 [get_ports {out[77]}]
set_load -pin_load 0.05 [get_ports {out[76]}]
set_load -pin_load 0.05 [get_ports {out[75]}]
set_load -pin_load 0.05 [get_ports {out[74]}]
set_load -pin_load 0.05 [get_ports {out[73]}]
set_load -pin_load 0.05 [get_ports {out[72]}]
set_load -pin_load 0.05 [get_ports {out[71]}]
set_load -pin_load 0.05 [get_ports {out[70]}]
set_load -pin_load 0.05 [get_ports {out[69]}]
set_load -pin_load 0.05 [get_ports {out[68]}]
set_load -pin_load 0.05 [get_ports {out[67]}]
set_load -pin_load 0.05 [get_ports {out[66]}]
set_load -pin_load 0.05 [get_ports {out[65]}]
set_load -pin_load 0.05 [get_ports {out[64]}]
set_load -pin_load 0.05 [get_ports {out[63]}]
set_load -pin_load 0.05 [get_ports {out[62]}]
set_load -pin_load 0.05 [get_ports {out[61]}]
set_load -pin_load 0.05 [get_ports {out[60]}]
set_load -pin_load 0.05 [get_ports {out[59]}]
set_load -pin_load 0.05 [get_ports {out[58]}]
set_load -pin_load 0.05 [get_ports {out[57]}]
set_load -pin_load 0.05 [get_ports {out[56]}]
set_load -pin_load 0.05 [get_ports {out[55]}]
set_load -pin_load 0.05 [get_ports {out[54]}]
set_load -pin_load 0.05 [get_ports {out[53]}]
set_load -pin_load 0.05 [get_ports {out[52]}]
set_load -pin_load 0.05 [get_ports {out[51]}]
set_load -pin_load 0.05 [get_ports {out[50]}]
set_load -pin_load 0.05 [get_ports {out[49]}]
set_load -pin_load 0.05 [get_ports {out[48]}]
set_load -pin_load 0.05 [get_ports {out[47]}]
set_load -pin_load 0.05 [get_ports {out[46]}]
set_load -pin_load 0.05 [get_ports {out[45]}]
set_load -pin_load 0.05 [get_ports {out[44]}]
set_load -pin_load 0.05 [get_ports {out[43]}]
set_load -pin_load 0.05 [get_ports {out[42]}]
set_load -pin_load 0.05 [get_ports {out[41]}]
set_load -pin_load 0.05 [get_ports {out[40]}]
set_load -pin_load 0.05 [get_ports {out[39]}]
set_load -pin_load 0.05 [get_ports {out[38]}]
set_load -pin_load 0.05 [get_ports {out[37]}]
set_load -pin_load 0.05 [get_ports {out[36]}]
set_load -pin_load 0.05 [get_ports {out[35]}]
set_load -pin_load 0.05 [get_ports {out[34]}]
set_load -pin_load 0.05 [get_ports {out[33]}]
set_load -pin_load 0.05 [get_ports {out[32]}]
set_load -pin_load 0.05 [get_ports {out[31]}]
set_load -pin_load 0.05 [get_ports {out[30]}]
set_load -pin_load 0.05 [get_ports {out[29]}]
set_load -pin_load 0.05 [get_ports {out[28]}]
set_load -pin_load 0.05 [get_ports {out[27]}]
set_load -pin_load 0.05 [get_ports {out[26]}]
set_load -pin_load 0.05 [get_ports {out[25]}]
set_load -pin_load 0.05 [get_ports {out[24]}]
set_load -pin_load 0.05 [get_ports {out[23]}]
set_load -pin_load 0.05 [get_ports {out[22]}]
set_load -pin_load 0.05 [get_ports {out[21]}]
set_load -pin_load 0.05 [get_ports {out[20]}]
set_load -pin_load 0.05 [get_ports {out[19]}]
set_load -pin_load 0.05 [get_ports {out[18]}]
set_load -pin_load 0.05 [get_ports {out[17]}]
set_load -pin_load 0.05 [get_ports {out[16]}]
set_load -pin_load 0.05 [get_ports {out[15]}]
set_load -pin_load 0.05 [get_ports {out[14]}]
set_load -pin_load 0.05 [get_ports {out[13]}]
set_load -pin_load 0.05 [get_ports {out[12]}]
set_load -pin_load 0.05 [get_ports {out[11]}]
set_load -pin_load 0.05 [get_ports {out[10]}]
set_load -pin_load 0.05 [get_ports {out[9]}]
set_load -pin_load 0.05 [get_ports {out[8]}]
set_load -pin_load 0.05 [get_ports {out[7]}]
set_load -pin_load 0.05 [get_ports {out[6]}]
set_load -pin_load 0.05 [get_ports {out[5]}]
set_load -pin_load 0.05 [get_ports {out[4]}]
set_load -pin_load 0.05 [get_ports {out[3]}]
set_load -pin_load 0.05 [get_ports {out[2]}]
set_load -pin_load 0.05 [get_ports {out[1]}]
set_load -pin_load 0.05 [get_ports {out[0]}]
set_max_capacitance 0.15 [get_ports {in_1[46]}]
set_max_capacitance 0.15 [get_ports {in_1[45]}]
set_max_capacitance 0.15 [get_ports {in_1[44]}]
set_max_capacitance 0.15 [get_ports {in_1[43]}]
set_max_capacitance 0.15 [get_ports {in_1[42]}]
set_max_capacitance 0.15 [get_ports {in_1[41]}]
set_max_capacitance 0.15 [get_ports {in_1[40]}]
set_max_capacitance 0.15 [get_ports {in_1[39]}]
set_max_capacitance 0.15 [get_ports {in_1[38]}]
set_max_capacitance 0.15 [get_ports {in_1[37]}]
set_max_capacitance 0.15 [get_ports {in_1[36]}]
set_max_capacitance 0.15 [get_ports {in_1[35]}]
set_max_capacitance 0.15 [get_ports {in_1[34]}]
set_max_capacitance 0.15 [get_ports {in_1[33]}]
set_max_capacitance 0.15 [get_ports {in_1[32]}]
set_max_capacitance 0.15 [get_ports {in_1[31]}]
set_max_capacitance 0.15 [get_ports {in_1[30]}]
set_max_capacitance 0.15 [get_ports {in_1[29]}]
set_max_capacitance 0.15 [get_ports {in_1[28]}]
set_max_capacitance 0.15 [get_ports {in_1[27]}]
set_max_capacitance 0.15 [get_ports {in_1[26]}]
set_max_capacitance 0.15 [get_ports {in_1[25]}]
set_max_capacitance 0.15 [get_ports {in_1[24]}]
set_max_capacitance 0.15 [get_ports {in_1[23]}]
set_max_capacitance 0.15 [get_ports {in_1[22]}]
set_max_capacitance 0.15 [get_ports {in_1[21]}]
set_max_capacitance 0.15 [get_ports {in_1[20]}]
set_max_capacitance 0.15 [get_ports {in_1[19]}]
set_max_capacitance 0.15 [get_ports {in_1[18]}]
set_max_capacitance 0.15 [get_ports {in_1[17]}]
set_max_capacitance 0.15 [get_ports {in_1[16]}]
set_max_capacitance 0.15 [get_ports {in_1[15]}]
set_max_capacitance 0.15 [get_ports {in_1[14]}]
set_max_capacitance 0.15 [get_ports {in_1[13]}]
set_max_capacitance 0.15 [get_ports {in_1[12]}]
set_max_capacitance 0.15 [get_ports {in_1[11]}]
set_max_capacitance 0.15 [get_ports {in_1[10]}]
set_max_capacitance 0.15 [get_ports {in_1[9]}]
set_max_capacitance 0.15 [get_ports {in_1[8]}]
set_max_capacitance 0.15 [get_ports {in_1[7]}]
set_max_capacitance 0.15 [get_ports {in_1[6]}]
set_max_capacitance 0.15 [get_ports {in_1[5]}]
set_max_capacitance 0.15 [get_ports {in_1[4]}]
set_max_capacitance 0.15 [get_ports {in_1[3]}]
set_max_capacitance 0.15 [get_ports {in_1[2]}]
set_max_capacitance 0.15 [get_ports {in_1[1]}]
set_max_capacitance 0.15 [get_ports {in_1[0]}]
set_max_capacitance 0.15 [get_ports {in_2[46]}]
set_max_capacitance 0.15 [get_ports {in_2[45]}]
set_max_capacitance 0.15 [get_ports {in_2[44]}]
set_max_capacitance 0.15 [get_ports {in_2[43]}]
set_max_capacitance 0.15 [get_ports {in_2[42]}]
set_max_capacitance 0.15 [get_ports {in_2[41]}]
set_max_capacitance 0.15 [get_ports {in_2[40]}]
set_max_capacitance 0.15 [get_ports {in_2[39]}]
set_max_capacitance 0.15 [get_ports {in_2[38]}]
set_max_capacitance 0.15 [get_ports {in_2[37]}]
set_max_capacitance 0.15 [get_ports {in_2[36]}]
set_max_capacitance 0.15 [get_ports {in_2[35]}]
set_max_capacitance 0.15 [get_ports {in_2[34]}]
set_max_capacitance 0.15 [get_ports {in_2[33]}]
set_max_capacitance 0.15 [get_ports {in_2[32]}]
set_max_capacitance 0.15 [get_ports {in_2[31]}]
set_max_capacitance 0.15 [get_ports {in_2[30]}]
set_max_capacitance 0.15 [get_ports {in_2[29]}]
set_max_capacitance 0.15 [get_ports {in_2[28]}]
set_max_capacitance 0.15 [get_ports {in_2[27]}]
set_max_capacitance 0.15 [get_ports {in_2[26]}]
set_max_capacitance 0.15 [get_ports {in_2[25]}]
set_max_capacitance 0.15 [get_ports {in_2[24]}]
set_max_capacitance 0.15 [get_ports {in_2[23]}]
set_max_capacitance 0.15 [get_ports {in_2[22]}]
set_max_capacitance 0.15 [get_ports {in_2[21]}]
set_max_capacitance 0.15 [get_ports {in_2[20]}]
set_max_capacitance 0.15 [get_ports {in_2[19]}]
set_max_capacitance 0.15 [get_ports {in_2[18]}]
set_max_capacitance 0.15 [get_ports {in_2[17]}]
set_max_capacitance 0.15 [get_ports {in_2[16]}]
set_max_capacitance 0.15 [get_ports {in_2[15]}]
set_max_capacitance 0.15 [get_ports {in_2[14]}]
set_max_capacitance 0.15 [get_ports {in_2[13]}]
set_max_capacitance 0.15 [get_ports {in_2[12]}]
set_max_capacitance 0.15 [get_ports {in_2[11]}]
set_max_capacitance 0.15 [get_ports {in_2[10]}]
set_max_capacitance 0.15 [get_ports {in_2[9]}]
set_max_capacitance 0.15 [get_ports {in_2[8]}]
set_max_capacitance 0.15 [get_ports {in_2[7]}]
set_max_capacitance 0.15 [get_ports {in_2[6]}]
set_max_capacitance 0.15 [get_ports {in_2[5]}]
set_max_capacitance 0.15 [get_ports {in_2[4]}]
set_max_capacitance 0.15 [get_ports {in_2[3]}]
set_max_capacitance 0.15 [get_ports {in_2[2]}]
set_max_capacitance 0.15 [get_ports {in_2[1]}]
set_max_capacitance 0.15 [get_ports {in_2[0]}]
set_max_capacitance 0.15 [get_ports {in_3[47]}]
set_max_capacitance 0.15 [get_ports {in_3[46]}]
set_max_capacitance 0.15 [get_ports {in_3[45]}]
set_max_capacitance 0.15 [get_ports {in_3[44]}]
set_max_capacitance 0.15 [get_ports {in_3[43]}]
set_max_capacitance 0.15 [get_ports {in_3[42]}]
set_max_capacitance 0.15 [get_ports {in_3[41]}]
set_max_capacitance 0.15 [get_ports {in_3[40]}]
set_max_capacitance 0.15 [get_ports {in_3[39]}]
set_max_capacitance 0.15 [get_ports {in_3[38]}]
set_max_capacitance 0.15 [get_ports {in_3[37]}]
set_max_capacitance 0.15 [get_ports {in_3[36]}]
set_max_capacitance 0.15 [get_ports {in_3[35]}]
set_max_capacitance 0.15 [get_ports {in_3[34]}]
set_max_capacitance 0.15 [get_ports {in_3[33]}]
set_max_capacitance 0.15 [get_ports {in_3[32]}]
set_max_capacitance 0.15 [get_ports {in_3[31]}]
set_max_capacitance 0.15 [get_ports {in_3[30]}]
set_max_capacitance 0.15 [get_ports {in_3[29]}]
set_max_capacitance 0.15 [get_ports {in_3[28]}]
set_max_capacitance 0.15 [get_ports {in_3[27]}]
set_max_capacitance 0.15 [get_ports {in_3[26]}]
set_max_capacitance 0.15 [get_ports {in_3[25]}]
set_max_capacitance 0.15 [get_ports {in_3[24]}]
set_max_capacitance 0.15 [get_ports {in_3[23]}]
set_max_capacitance 0.15 [get_ports {in_3[22]}]
set_max_capacitance 0.15 [get_ports {in_3[21]}]
set_max_capacitance 0.15 [get_ports {in_3[20]}]
set_max_capacitance 0.15 [get_ports {in_3[19]}]
set_max_capacitance 0.15 [get_ports {in_3[18]}]
set_max_capacitance 0.15 [get_ports {in_3[17]}]
set_max_capacitance 0.15 [get_ports {in_3[16]}]
set_max_capacitance 0.15 [get_ports {in_3[15]}]
set_max_capacitance 0.15 [get_ports {in_3[14]}]
set_max_capacitance 0.15 [get_ports {in_3[13]}]
set_max_capacitance 0.15 [get_ports {in_3[12]}]
set_max_capacitance 0.15 [get_ports {in_3[11]}]
set_max_capacitance 0.15 [get_ports {in_3[10]}]
set_max_capacitance 0.15 [get_ports {in_3[9]}]
set_max_capacitance 0.15 [get_ports {in_3[8]}]
set_max_capacitance 0.15 [get_ports {in_3[7]}]
set_max_capacitance 0.15 [get_ports {in_3[6]}]
set_max_capacitance 0.15 [get_ports {in_3[5]}]
set_max_capacitance 0.15 [get_ports {in_3[4]}]
set_max_capacitance 0.15 [get_ports {in_3[3]}]
set_max_capacitance 0.15 [get_ports {in_3[2]}]
set_max_capacitance 0.15 [get_ports {in_3[1]}]
set_max_capacitance 0.15 [get_ports {in_3[0]}]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports clk]
set_max_fanout 10 [get_ports {in_1[46]}]
set_max_fanout 10 [get_ports {in_1[45]}]
set_max_fanout 10 [get_ports {in_1[44]}]
set_max_fanout 10 [get_ports {in_1[43]}]
set_max_fanout 10 [get_ports {in_1[42]}]
set_max_fanout 10 [get_ports {in_1[41]}]
set_max_fanout 10 [get_ports {in_1[40]}]
set_max_fanout 10 [get_ports {in_1[39]}]
set_max_fanout 10 [get_ports {in_1[38]}]
set_max_fanout 10 [get_ports {in_1[37]}]
set_max_fanout 10 [get_ports {in_1[36]}]
set_max_fanout 10 [get_ports {in_1[35]}]
set_max_fanout 10 [get_ports {in_1[34]}]
set_max_fanout 10 [get_ports {in_1[33]}]
set_max_fanout 10 [get_ports {in_1[32]}]
set_max_fanout 10 [get_ports {in_1[31]}]
set_max_fanout 10 [get_ports {in_1[30]}]
set_max_fanout 10 [get_ports {in_1[29]}]
set_max_fanout 10 [get_ports {in_1[28]}]
set_max_fanout 10 [get_ports {in_1[27]}]
set_max_fanout 10 [get_ports {in_1[26]}]
set_max_fanout 10 [get_ports {in_1[25]}]
set_max_fanout 10 [get_ports {in_1[24]}]
set_max_fanout 10 [get_ports {in_1[23]}]
set_max_fanout 10 [get_ports {in_1[22]}]
set_max_fanout 10 [get_ports {in_1[21]}]
set_max_fanout 10 [get_ports {in_1[20]}]
set_max_fanout 10 [get_ports {in_1[19]}]
set_max_fanout 10 [get_ports {in_1[18]}]
set_max_fanout 10 [get_ports {in_1[17]}]
set_max_fanout 10 [get_ports {in_1[16]}]
set_max_fanout 10 [get_ports {in_1[15]}]
set_max_fanout 10 [get_ports {in_1[14]}]
set_max_fanout 10 [get_ports {in_1[13]}]
set_max_fanout 10 [get_ports {in_1[12]}]
set_max_fanout 10 [get_ports {in_1[11]}]
set_max_fanout 10 [get_ports {in_1[10]}]
set_max_fanout 10 [get_ports {in_1[9]}]
set_max_fanout 10 [get_ports {in_1[8]}]
set_max_fanout 10 [get_ports {in_1[7]}]
set_max_fanout 10 [get_ports {in_1[6]}]
set_max_fanout 10 [get_ports {in_1[5]}]
set_max_fanout 10 [get_ports {in_1[4]}]
set_max_fanout 10 [get_ports {in_1[3]}]
set_max_fanout 10 [get_ports {in_1[2]}]
set_max_fanout 10 [get_ports {in_1[1]}]
set_max_fanout 10 [get_ports {in_1[0]}]
set_max_fanout 10 [get_ports {in_2[46]}]
set_max_fanout 10 [get_ports {in_2[45]}]
set_max_fanout 10 [get_ports {in_2[44]}]
set_max_fanout 10 [get_ports {in_2[43]}]
set_max_fanout 10 [get_ports {in_2[42]}]
set_max_fanout 10 [get_ports {in_2[41]}]
set_max_fanout 10 [get_ports {in_2[40]}]
set_max_fanout 10 [get_ports {in_2[39]}]
set_max_fanout 10 [get_ports {in_2[38]}]
set_max_fanout 10 [get_ports {in_2[37]}]
set_max_fanout 10 [get_ports {in_2[36]}]
set_max_fanout 10 [get_ports {in_2[35]}]
set_max_fanout 10 [get_ports {in_2[34]}]
set_max_fanout 10 [get_ports {in_2[33]}]
set_max_fanout 10 [get_ports {in_2[32]}]
set_max_fanout 10 [get_ports {in_2[31]}]
set_max_fanout 10 [get_ports {in_2[30]}]
set_max_fanout 10 [get_ports {in_2[29]}]
set_max_fanout 10 [get_ports {in_2[28]}]
set_max_fanout 10 [get_ports {in_2[27]}]
set_max_fanout 10 [get_ports {in_2[26]}]
set_max_fanout 10 [get_ports {in_2[25]}]
set_max_fanout 10 [get_ports {in_2[24]}]
set_max_fanout 10 [get_ports {in_2[23]}]
set_max_fanout 10 [get_ports {in_2[22]}]
set_max_fanout 10 [get_ports {in_2[21]}]
set_max_fanout 10 [get_ports {in_2[20]}]
set_max_fanout 10 [get_ports {in_2[19]}]
set_max_fanout 10 [get_ports {in_2[18]}]
set_max_fanout 10 [get_ports {in_2[17]}]
set_max_fanout 10 [get_ports {in_2[16]}]
set_max_fanout 10 [get_ports {in_2[15]}]
set_max_fanout 10 [get_ports {in_2[14]}]
set_max_fanout 10 [get_ports {in_2[13]}]
set_max_fanout 10 [get_ports {in_2[12]}]
set_max_fanout 10 [get_ports {in_2[11]}]
set_max_fanout 10 [get_ports {in_2[10]}]
set_max_fanout 10 [get_ports {in_2[9]}]
set_max_fanout 10 [get_ports {in_2[8]}]
set_max_fanout 10 [get_ports {in_2[7]}]
set_max_fanout 10 [get_ports {in_2[6]}]
set_max_fanout 10 [get_ports {in_2[5]}]
set_max_fanout 10 [get_ports {in_2[4]}]
set_max_fanout 10 [get_ports {in_2[3]}]
set_max_fanout 10 [get_ports {in_2[2]}]
set_max_fanout 10 [get_ports {in_2[1]}]
set_max_fanout 10 [get_ports {in_2[0]}]
set_max_fanout 10 [get_ports {in_3[47]}]
set_max_fanout 10 [get_ports {in_3[46]}]
set_max_fanout 10 [get_ports {in_3[45]}]
set_max_fanout 10 [get_ports {in_3[44]}]
set_max_fanout 10 [get_ports {in_3[43]}]
set_max_fanout 10 [get_ports {in_3[42]}]
set_max_fanout 10 [get_ports {in_3[41]}]
set_max_fanout 10 [get_ports {in_3[40]}]
set_max_fanout 10 [get_ports {in_3[39]}]
set_max_fanout 10 [get_ports {in_3[38]}]
set_max_fanout 10 [get_ports {in_3[37]}]
set_max_fanout 10 [get_ports {in_3[36]}]
set_max_fanout 10 [get_ports {in_3[35]}]
set_max_fanout 10 [get_ports {in_3[34]}]
set_max_fanout 10 [get_ports {in_3[33]}]
set_max_fanout 10 [get_ports {in_3[32]}]
set_max_fanout 10 [get_ports {in_3[31]}]
set_max_fanout 10 [get_ports {in_3[30]}]
set_max_fanout 10 [get_ports {in_3[29]}]
set_max_fanout 10 [get_ports {in_3[28]}]
set_max_fanout 10 [get_ports {in_3[27]}]
set_max_fanout 10 [get_ports {in_3[26]}]
set_max_fanout 10 [get_ports {in_3[25]}]
set_max_fanout 10 [get_ports {in_3[24]}]
set_max_fanout 10 [get_ports {in_3[23]}]
set_max_fanout 10 [get_ports {in_3[22]}]
set_max_fanout 10 [get_ports {in_3[21]}]
set_max_fanout 10 [get_ports {in_3[20]}]
set_max_fanout 10 [get_ports {in_3[19]}]
set_max_fanout 10 [get_ports {in_3[18]}]
set_max_fanout 10 [get_ports {in_3[17]}]
set_max_fanout 10 [get_ports {in_3[16]}]
set_max_fanout 10 [get_ports {in_3[15]}]
set_max_fanout 10 [get_ports {in_3[14]}]
set_max_fanout 10 [get_ports {in_3[13]}]
set_max_fanout 10 [get_ports {in_3[12]}]
set_max_fanout 10 [get_ports {in_3[11]}]
set_max_fanout 10 [get_ports {in_3[10]}]
set_max_fanout 10 [get_ports {in_3[9]}]
set_max_fanout 10 [get_ports {in_3[8]}]
set_max_fanout 10 [get_ports {in_3[7]}]
set_max_fanout 10 [get_ports {in_3[6]}]
set_max_fanout 10 [get_ports {in_3[5]}]
set_max_fanout 10 [get_ports {in_3[4]}]
set_max_fanout 10 [get_ports {in_3[3]}]
set_max_fanout 10 [get_ports {in_3[2]}]
set_max_fanout 10 [get_ports {in_3[1]}]
set_max_fanout 10 [get_ports {in_3[0]}]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports clk]
set_max_transition 3 [get_ports {in_1[46]}]
set_max_transition 3 [get_ports {in_1[45]}]
set_max_transition 3 [get_ports {in_1[44]}]
set_max_transition 3 [get_ports {in_1[43]}]
set_max_transition 3 [get_ports {in_1[42]}]
set_max_transition 3 [get_ports {in_1[41]}]
set_max_transition 3 [get_ports {in_1[40]}]
set_max_transition 3 [get_ports {in_1[39]}]
set_max_transition 3 [get_ports {in_1[38]}]
set_max_transition 3 [get_ports {in_1[37]}]
set_max_transition 3 [get_ports {in_1[36]}]
set_max_transition 3 [get_ports {in_1[35]}]
set_max_transition 3 [get_ports {in_1[34]}]
set_max_transition 3 [get_ports {in_1[33]}]
set_max_transition 3 [get_ports {in_1[32]}]
set_max_transition 3 [get_ports {in_1[31]}]
set_max_transition 3 [get_ports {in_1[30]}]
set_max_transition 3 [get_ports {in_1[29]}]
set_max_transition 3 [get_ports {in_1[28]}]
set_max_transition 3 [get_ports {in_1[27]}]
set_max_transition 3 [get_ports {in_1[26]}]
set_max_transition 3 [get_ports {in_1[25]}]
set_max_transition 3 [get_ports {in_1[24]}]
set_max_transition 3 [get_ports {in_1[23]}]
set_max_transition 3 [get_ports {in_1[22]}]
set_max_transition 3 [get_ports {in_1[21]}]
set_max_transition 3 [get_ports {in_1[20]}]
set_max_transition 3 [get_ports {in_1[19]}]
set_max_transition 3 [get_ports {in_1[18]}]
set_max_transition 3 [get_ports {in_1[17]}]
set_max_transition 3 [get_ports {in_1[16]}]
set_max_transition 3 [get_ports {in_1[15]}]
set_max_transition 3 [get_ports {in_1[14]}]
set_max_transition 3 [get_ports {in_1[13]}]
set_max_transition 3 [get_ports {in_1[12]}]
set_max_transition 3 [get_ports {in_1[11]}]
set_max_transition 3 [get_ports {in_1[10]}]
set_max_transition 3 [get_ports {in_1[9]}]
set_max_transition 3 [get_ports {in_1[8]}]
set_max_transition 3 [get_ports {in_1[7]}]
set_max_transition 3 [get_ports {in_1[6]}]
set_max_transition 3 [get_ports {in_1[5]}]
set_max_transition 3 [get_ports {in_1[4]}]
set_max_transition 3 [get_ports {in_1[3]}]
set_max_transition 3 [get_ports {in_1[2]}]
set_max_transition 3 [get_ports {in_1[1]}]
set_max_transition 3 [get_ports {in_1[0]}]
set_max_transition 3 [get_ports {in_2[46]}]
set_max_transition 3 [get_ports {in_2[45]}]
set_max_transition 3 [get_ports {in_2[44]}]
set_max_transition 3 [get_ports {in_2[43]}]
set_max_transition 3 [get_ports {in_2[42]}]
set_max_transition 3 [get_ports {in_2[41]}]
set_max_transition 3 [get_ports {in_2[40]}]
set_max_transition 3 [get_ports {in_2[39]}]
set_max_transition 3 [get_ports {in_2[38]}]
set_max_transition 3 [get_ports {in_2[37]}]
set_max_transition 3 [get_ports {in_2[36]}]
set_max_transition 3 [get_ports {in_2[35]}]
set_max_transition 3 [get_ports {in_2[34]}]
set_max_transition 3 [get_ports {in_2[33]}]
set_max_transition 3 [get_ports {in_2[32]}]
set_max_transition 3 [get_ports {in_2[31]}]
set_max_transition 3 [get_ports {in_2[30]}]
set_max_transition 3 [get_ports {in_2[29]}]
set_max_transition 3 [get_ports {in_2[28]}]
set_max_transition 3 [get_ports {in_2[27]}]
set_max_transition 3 [get_ports {in_2[26]}]
set_max_transition 3 [get_ports {in_2[25]}]
set_max_transition 3 [get_ports {in_2[24]}]
set_max_transition 3 [get_ports {in_2[23]}]
set_max_transition 3 [get_ports {in_2[22]}]
set_max_transition 3 [get_ports {in_2[21]}]
set_max_transition 3 [get_ports {in_2[20]}]
set_max_transition 3 [get_ports {in_2[19]}]
set_max_transition 3 [get_ports {in_2[18]}]
set_max_transition 3 [get_ports {in_2[17]}]
set_max_transition 3 [get_ports {in_2[16]}]
set_max_transition 3 [get_ports {in_2[15]}]
set_max_transition 3 [get_ports {in_2[14]}]
set_max_transition 3 [get_ports {in_2[13]}]
set_max_transition 3 [get_ports {in_2[12]}]
set_max_transition 3 [get_ports {in_2[11]}]
set_max_transition 3 [get_ports {in_2[10]}]
set_max_transition 3 [get_ports {in_2[9]}]
set_max_transition 3 [get_ports {in_2[8]}]
set_max_transition 3 [get_ports {in_2[7]}]
set_max_transition 3 [get_ports {in_2[6]}]
set_max_transition 3 [get_ports {in_2[5]}]
set_max_transition 3 [get_ports {in_2[4]}]
set_max_transition 3 [get_ports {in_2[3]}]
set_max_transition 3 [get_ports {in_2[2]}]
set_max_transition 3 [get_ports {in_2[1]}]
set_max_transition 3 [get_ports {in_2[0]}]
set_max_transition 3 [get_ports {in_3[47]}]
set_max_transition 3 [get_ports {in_3[46]}]
set_max_transition 3 [get_ports {in_3[45]}]
set_max_transition 3 [get_ports {in_3[44]}]
set_max_transition 3 [get_ports {in_3[43]}]
set_max_transition 3 [get_ports {in_3[42]}]
set_max_transition 3 [get_ports {in_3[41]}]
set_max_transition 3 [get_ports {in_3[40]}]
set_max_transition 3 [get_ports {in_3[39]}]
set_max_transition 3 [get_ports {in_3[38]}]
set_max_transition 3 [get_ports {in_3[37]}]
set_max_transition 3 [get_ports {in_3[36]}]
set_max_transition 3 [get_ports {in_3[35]}]
set_max_transition 3 [get_ports {in_3[34]}]
set_max_transition 3 [get_ports {in_3[33]}]
set_max_transition 3 [get_ports {in_3[32]}]
set_max_transition 3 [get_ports {in_3[31]}]
set_max_transition 3 [get_ports {in_3[30]}]
set_max_transition 3 [get_ports {in_3[29]}]
set_max_transition 3 [get_ports {in_3[28]}]
set_max_transition 3 [get_ports {in_3[27]}]
set_max_transition 3 [get_ports {in_3[26]}]
set_max_transition 3 [get_ports {in_3[25]}]
set_max_transition 3 [get_ports {in_3[24]}]
set_max_transition 3 [get_ports {in_3[23]}]
set_max_transition 3 [get_ports {in_3[22]}]
set_max_transition 3 [get_ports {in_3[21]}]
set_max_transition 3 [get_ports {in_3[20]}]
set_max_transition 3 [get_ports {in_3[19]}]
set_max_transition 3 [get_ports {in_3[18]}]
set_max_transition 3 [get_ports {in_3[17]}]
set_max_transition 3 [get_ports {in_3[16]}]
set_max_transition 3 [get_ports {in_3[15]}]
set_max_transition 3 [get_ports {in_3[14]}]
set_max_transition 3 [get_ports {in_3[13]}]
set_max_transition 3 [get_ports {in_3[12]}]
set_max_transition 3 [get_ports {in_3[11]}]
set_max_transition 3 [get_ports {in_3[10]}]
set_max_transition 3 [get_ports {in_3[9]}]
set_max_transition 3 [get_ports {in_3[8]}]
set_max_transition 3 [get_ports {in_3[7]}]
set_max_transition 3 [get_ports {in_3[6]}]
set_max_transition 3 [get_ports {in_3[5]}]
set_max_transition 3 [get_ports {in_3[4]}]
set_max_transition 3 [get_ports {in_3[3]}]
set_max_transition 3 [get_ports {in_3[2]}]
set_max_transition 3 [get_ports {in_3[1]}]
set_max_transition 3 [get_ports {in_3[0]}]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports clk]
create_clock [get_ports clk]  -period 5  -waveform {0 2.5}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[46]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[46]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[45]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[45]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[44]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[44]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[43]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[43]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[42]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[42]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[41]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[41]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[40]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[40]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[39]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[39]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[38]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[38]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[37]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[37]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[36]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[36]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[35]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[35]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[34]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[34]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[33]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[33]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[32]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[32]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[31]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[31]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[30]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[30]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[29]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[29]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[28]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[28]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[27]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[27]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[26]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[26]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[25]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[25]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[24]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[24]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[23]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[23]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[22]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[22]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[21]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[21]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[20]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[20]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[19]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[19]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[18]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[18]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[17]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[17]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[16]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[16]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[15]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[15]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[14]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[14]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[13]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[13]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[12]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[12]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[11]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[11]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[10]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[10]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[9]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[9]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[8]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[8]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[7]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[6]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[5]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[4]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[3]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[2]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[1]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_1[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_1[0]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[46]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[46]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[45]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[45]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[44]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[44]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[43]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[43]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[42]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[42]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[41]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[41]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[40]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[40]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[39]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[39]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[38]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[38]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[37]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[37]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[36]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[36]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[35]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[35]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[34]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[34]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[33]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[33]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[32]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[32]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[31]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[31]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[30]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[30]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[29]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[29]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[28]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[28]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[27]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[27]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[26]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[26]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[25]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[25]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[24]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[24]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[23]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[23]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[22]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[22]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[21]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[21]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[20]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[20]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[19]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[19]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[18]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[18]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[17]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[17]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[16]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[16]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[15]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[15]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[14]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[14]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[13]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[13]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[12]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[12]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[11]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[11]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[10]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[10]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[9]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[9]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[8]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[8]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[7]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[6]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[5]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[4]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[3]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[2]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[1]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_2[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_2[0]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[47]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[47]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[46]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[46]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[45]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[45]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[44]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[44]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[43]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[43]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[42]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[42]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[41]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[41]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[40]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[40]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[39]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[39]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[38]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[38]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[37]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[37]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[36]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[36]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[35]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[35]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[34]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[34]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[33]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[33]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[32]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[32]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[31]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[31]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[30]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[30]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[29]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[29]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[28]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[28]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[27]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[27]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[26]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[26]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[25]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[25]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[24]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[24]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[23]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[23]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[22]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[22]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[21]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[21]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[20]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[20]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[19]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[19]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[18]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[18]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[17]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[17]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[16]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[16]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[15]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[15]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[14]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[14]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[13]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[13]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[12]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[12]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[11]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[11]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[10]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[10]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[9]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[9]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[8]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[8]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[7]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[6]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[5]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[4]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[3]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[2]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[1]}]
set_input_delay -clock clk  -max 2.5  [get_ports {in_3[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_3[0]}]
set_input_delay -clock clk  -max 2.5  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  0  [get_ports rst_n]
set_output_delay -clock clk  -max 2.5  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 2.5  [get_ports {out[95]}]
set_output_delay -clock clk  -min 0  [get_ports {out[95]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[94]}]
set_output_delay -clock clk  -min 0  [get_ports {out[94]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[93]}]
set_output_delay -clock clk  -min 0  [get_ports {out[93]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[92]}]
set_output_delay -clock clk  -min 0  [get_ports {out[92]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[91]}]
set_output_delay -clock clk  -min 0  [get_ports {out[91]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[90]}]
set_output_delay -clock clk  -min 0  [get_ports {out[90]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[89]}]
set_output_delay -clock clk  -min 0  [get_ports {out[89]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[88]}]
set_output_delay -clock clk  -min 0  [get_ports {out[88]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[87]}]
set_output_delay -clock clk  -min 0  [get_ports {out[87]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[86]}]
set_output_delay -clock clk  -min 0  [get_ports {out[86]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[85]}]
set_output_delay -clock clk  -min 0  [get_ports {out[85]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[84]}]
set_output_delay -clock clk  -min 0  [get_ports {out[84]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[83]}]
set_output_delay -clock clk  -min 0  [get_ports {out[83]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[82]}]
set_output_delay -clock clk  -min 0  [get_ports {out[82]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[81]}]
set_output_delay -clock clk  -min 0  [get_ports {out[81]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[80]}]
set_output_delay -clock clk  -min 0  [get_ports {out[80]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[79]}]
set_output_delay -clock clk  -min 0  [get_ports {out[79]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[78]}]
set_output_delay -clock clk  -min 0  [get_ports {out[78]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[77]}]
set_output_delay -clock clk  -min 0  [get_ports {out[77]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[76]}]
set_output_delay -clock clk  -min 0  [get_ports {out[76]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[75]}]
set_output_delay -clock clk  -min 0  [get_ports {out[75]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[74]}]
set_output_delay -clock clk  -min 0  [get_ports {out[74]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[73]}]
set_output_delay -clock clk  -min 0  [get_ports {out[73]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[72]}]
set_output_delay -clock clk  -min 0  [get_ports {out[72]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[71]}]
set_output_delay -clock clk  -min 0  [get_ports {out[71]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[70]}]
set_output_delay -clock clk  -min 0  [get_ports {out[70]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[69]}]
set_output_delay -clock clk  -min 0  [get_ports {out[69]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[68]}]
set_output_delay -clock clk  -min 0  [get_ports {out[68]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[67]}]
set_output_delay -clock clk  -min 0  [get_ports {out[67]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[66]}]
set_output_delay -clock clk  -min 0  [get_ports {out[66]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[65]}]
set_output_delay -clock clk  -min 0  [get_ports {out[65]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[64]}]
set_output_delay -clock clk  -min 0  [get_ports {out[64]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[63]}]
set_output_delay -clock clk  -min 0  [get_ports {out[63]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[62]}]
set_output_delay -clock clk  -min 0  [get_ports {out[62]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[61]}]
set_output_delay -clock clk  -min 0  [get_ports {out[61]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[60]}]
set_output_delay -clock clk  -min 0  [get_ports {out[60]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[59]}]
set_output_delay -clock clk  -min 0  [get_ports {out[59]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[58]}]
set_output_delay -clock clk  -min 0  [get_ports {out[58]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[57]}]
set_output_delay -clock clk  -min 0  [get_ports {out[57]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[56]}]
set_output_delay -clock clk  -min 0  [get_ports {out[56]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[55]}]
set_output_delay -clock clk  -min 0  [get_ports {out[55]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[54]}]
set_output_delay -clock clk  -min 0  [get_ports {out[54]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[53]}]
set_output_delay -clock clk  -min 0  [get_ports {out[53]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[52]}]
set_output_delay -clock clk  -min 0  [get_ports {out[52]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[51]}]
set_output_delay -clock clk  -min 0  [get_ports {out[51]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[50]}]
set_output_delay -clock clk  -min 0  [get_ports {out[50]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[49]}]
set_output_delay -clock clk  -min 0  [get_ports {out[49]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[48]}]
set_output_delay -clock clk  -min 0  [get_ports {out[48]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[47]}]
set_output_delay -clock clk  -min 0  [get_ports {out[47]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[46]}]
set_output_delay -clock clk  -min 0  [get_ports {out[46]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[45]}]
set_output_delay -clock clk  -min 0  [get_ports {out[45]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[44]}]
set_output_delay -clock clk  -min 0  [get_ports {out[44]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[43]}]
set_output_delay -clock clk  -min 0  [get_ports {out[43]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[42]}]
set_output_delay -clock clk  -min 0  [get_ports {out[42]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[41]}]
set_output_delay -clock clk  -min 0  [get_ports {out[41]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[40]}]
set_output_delay -clock clk  -min 0  [get_ports {out[40]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[39]}]
set_output_delay -clock clk  -min 0  [get_ports {out[39]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[38]}]
set_output_delay -clock clk  -min 0  [get_ports {out[38]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[37]}]
set_output_delay -clock clk  -min 0  [get_ports {out[37]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[36]}]
set_output_delay -clock clk  -min 0  [get_ports {out[36]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[35]}]
set_output_delay -clock clk  -min 0  [get_ports {out[35]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[34]}]
set_output_delay -clock clk  -min 0  [get_ports {out[34]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[33]}]
set_output_delay -clock clk  -min 0  [get_ports {out[33]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[32]}]
set_output_delay -clock clk  -min 0  [get_ports {out[32]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[31]}]
set_output_delay -clock clk  -min 0  [get_ports {out[31]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[30]}]
set_output_delay -clock clk  -min 0  [get_ports {out[30]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[29]}]
set_output_delay -clock clk  -min 0  [get_ports {out[29]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[28]}]
set_output_delay -clock clk  -min 0  [get_ports {out[28]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[27]}]
set_output_delay -clock clk  -min 0  [get_ports {out[27]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[26]}]
set_output_delay -clock clk  -min 0  [get_ports {out[26]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[25]}]
set_output_delay -clock clk  -min 0  [get_ports {out[25]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[24]}]
set_output_delay -clock clk  -min 0  [get_ports {out[24]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[23]}]
set_output_delay -clock clk  -min 0  [get_ports {out[23]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[22]}]
set_output_delay -clock clk  -min 0  [get_ports {out[22]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[21]}]
set_output_delay -clock clk  -min 0  [get_ports {out[21]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[20]}]
set_output_delay -clock clk  -min 0  [get_ports {out[20]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[19]}]
set_output_delay -clock clk  -min 0  [get_ports {out[19]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[18]}]
set_output_delay -clock clk  -min 0  [get_ports {out[18]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[17]}]
set_output_delay -clock clk  -min 0  [get_ports {out[17]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[16]}]
set_output_delay -clock clk  -min 0  [get_ports {out[16]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[15]}]
set_output_delay -clock clk  -min 0  [get_ports {out[15]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[14]}]
set_output_delay -clock clk  -min 0  [get_ports {out[14]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[13]}]
set_output_delay -clock clk  -min 0  [get_ports {out[13]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[12]}]
set_output_delay -clock clk  -min 0  [get_ports {out[12]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[11]}]
set_output_delay -clock clk  -min 0  [get_ports {out[11]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[10]}]
set_output_delay -clock clk  -min 0  [get_ports {out[10]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[9]}]
set_output_delay -clock clk  -min 0  [get_ports {out[9]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[8]}]
set_output_delay -clock clk  -min 0  [get_ports {out[8]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[7]}]
set_output_delay -clock clk  -min 0  [get_ports {out[7]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[6]}]
set_output_delay -clock clk  -min 0  [get_ports {out[6]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[5]}]
set_output_delay -clock clk  -min 0  [get_ports {out[5]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[4]}]
set_output_delay -clock clk  -min 0  [get_ports {out[4]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[3]}]
set_output_delay -clock clk  -min 0  [get_ports {out[3]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[2]}]
set_output_delay -clock clk  -min 0  [get_ports {out[2]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[1]}]
set_output_delay -clock clk  -min 0  [get_ports {out[1]}]
set_output_delay -clock clk  -max 2.5  [get_ports {out[0]}]
set_output_delay -clock clk  -min 0  [get_ports {out[0]}]
set_input_transition -max 0.5  [get_ports {in_1[46]}]
set_input_transition -min 0.5  [get_ports {in_1[46]}]
set_input_transition -max 0.5  [get_ports {in_1[45]}]
set_input_transition -min 0.5  [get_ports {in_1[45]}]
set_input_transition -max 0.5  [get_ports {in_1[44]}]
set_input_transition -min 0.5  [get_ports {in_1[44]}]
set_input_transition -max 0.5  [get_ports {in_1[43]}]
set_input_transition -min 0.5  [get_ports {in_1[43]}]
set_input_transition -max 0.5  [get_ports {in_1[42]}]
set_input_transition -min 0.5  [get_ports {in_1[42]}]
set_input_transition -max 0.5  [get_ports {in_1[41]}]
set_input_transition -min 0.5  [get_ports {in_1[41]}]
set_input_transition -max 0.5  [get_ports {in_1[40]}]
set_input_transition -min 0.5  [get_ports {in_1[40]}]
set_input_transition -max 0.5  [get_ports {in_1[39]}]
set_input_transition -min 0.5  [get_ports {in_1[39]}]
set_input_transition -max 0.5  [get_ports {in_1[38]}]
set_input_transition -min 0.5  [get_ports {in_1[38]}]
set_input_transition -max 0.5  [get_ports {in_1[37]}]
set_input_transition -min 0.5  [get_ports {in_1[37]}]
set_input_transition -max 0.5  [get_ports {in_1[36]}]
set_input_transition -min 0.5  [get_ports {in_1[36]}]
set_input_transition -max 0.5  [get_ports {in_1[35]}]
set_input_transition -min 0.5  [get_ports {in_1[35]}]
set_input_transition -max 0.5  [get_ports {in_1[34]}]
set_input_transition -min 0.5  [get_ports {in_1[34]}]
set_input_transition -max 0.5  [get_ports {in_1[33]}]
set_input_transition -min 0.5  [get_ports {in_1[33]}]
set_input_transition -max 0.5  [get_ports {in_1[32]}]
set_input_transition -min 0.5  [get_ports {in_1[32]}]
set_input_transition -max 0.5  [get_ports {in_1[31]}]
set_input_transition -min 0.5  [get_ports {in_1[31]}]
set_input_transition -max 0.5  [get_ports {in_1[30]}]
set_input_transition -min 0.5  [get_ports {in_1[30]}]
set_input_transition -max 0.5  [get_ports {in_1[29]}]
set_input_transition -min 0.5  [get_ports {in_1[29]}]
set_input_transition -max 0.5  [get_ports {in_1[28]}]
set_input_transition -min 0.5  [get_ports {in_1[28]}]
set_input_transition -max 0.5  [get_ports {in_1[27]}]
set_input_transition -min 0.5  [get_ports {in_1[27]}]
set_input_transition -max 0.5  [get_ports {in_1[26]}]
set_input_transition -min 0.5  [get_ports {in_1[26]}]
set_input_transition -max 0.5  [get_ports {in_1[25]}]
set_input_transition -min 0.5  [get_ports {in_1[25]}]
set_input_transition -max 0.5  [get_ports {in_1[24]}]
set_input_transition -min 0.5  [get_ports {in_1[24]}]
set_input_transition -max 0.5  [get_ports {in_1[23]}]
set_input_transition -min 0.5  [get_ports {in_1[23]}]
set_input_transition -max 0.5  [get_ports {in_1[22]}]
set_input_transition -min 0.5  [get_ports {in_1[22]}]
set_input_transition -max 0.5  [get_ports {in_1[21]}]
set_input_transition -min 0.5  [get_ports {in_1[21]}]
set_input_transition -max 0.5  [get_ports {in_1[20]}]
set_input_transition -min 0.5  [get_ports {in_1[20]}]
set_input_transition -max 0.5  [get_ports {in_1[19]}]
set_input_transition -min 0.5  [get_ports {in_1[19]}]
set_input_transition -max 0.5  [get_ports {in_1[18]}]
set_input_transition -min 0.5  [get_ports {in_1[18]}]
set_input_transition -max 0.5  [get_ports {in_1[17]}]
set_input_transition -min 0.5  [get_ports {in_1[17]}]
set_input_transition -max 0.5  [get_ports {in_1[16]}]
set_input_transition -min 0.5  [get_ports {in_1[16]}]
set_input_transition -max 0.5  [get_ports {in_1[15]}]
set_input_transition -min 0.5  [get_ports {in_1[15]}]
set_input_transition -max 0.5  [get_ports {in_1[14]}]
set_input_transition -min 0.5  [get_ports {in_1[14]}]
set_input_transition -max 0.5  [get_ports {in_1[13]}]
set_input_transition -min 0.5  [get_ports {in_1[13]}]
set_input_transition -max 0.5  [get_ports {in_1[12]}]
set_input_transition -min 0.5  [get_ports {in_1[12]}]
set_input_transition -max 0.5  [get_ports {in_1[11]}]
set_input_transition -min 0.5  [get_ports {in_1[11]}]
set_input_transition -max 0.5  [get_ports {in_1[10]}]
set_input_transition -min 0.5  [get_ports {in_1[10]}]
set_input_transition -max 0.5  [get_ports {in_1[9]}]
set_input_transition -min 0.5  [get_ports {in_1[9]}]
set_input_transition -max 0.5  [get_ports {in_1[8]}]
set_input_transition -min 0.5  [get_ports {in_1[8]}]
set_input_transition -max 0.5  [get_ports {in_1[7]}]
set_input_transition -min 0.5  [get_ports {in_1[7]}]
set_input_transition -max 0.5  [get_ports {in_1[6]}]
set_input_transition -min 0.5  [get_ports {in_1[6]}]
set_input_transition -max 0.5  [get_ports {in_1[5]}]
set_input_transition -min 0.5  [get_ports {in_1[5]}]
set_input_transition -max 0.5  [get_ports {in_1[4]}]
set_input_transition -min 0.5  [get_ports {in_1[4]}]
set_input_transition -max 0.5  [get_ports {in_1[3]}]
set_input_transition -min 0.5  [get_ports {in_1[3]}]
set_input_transition -max 0.5  [get_ports {in_1[2]}]
set_input_transition -min 0.5  [get_ports {in_1[2]}]
set_input_transition -max 0.5  [get_ports {in_1[1]}]
set_input_transition -min 0.5  [get_ports {in_1[1]}]
set_input_transition -max 0.5  [get_ports {in_1[0]}]
set_input_transition -min 0.5  [get_ports {in_1[0]}]
set_input_transition -max 0.5  [get_ports {in_2[46]}]
set_input_transition -min 0.5  [get_ports {in_2[46]}]
set_input_transition -max 0.5  [get_ports {in_2[45]}]
set_input_transition -min 0.5  [get_ports {in_2[45]}]
set_input_transition -max 0.5  [get_ports {in_2[44]}]
set_input_transition -min 0.5  [get_ports {in_2[44]}]
set_input_transition -max 0.5  [get_ports {in_2[43]}]
set_input_transition -min 0.5  [get_ports {in_2[43]}]
set_input_transition -max 0.5  [get_ports {in_2[42]}]
set_input_transition -min 0.5  [get_ports {in_2[42]}]
set_input_transition -max 0.5  [get_ports {in_2[41]}]
set_input_transition -min 0.5  [get_ports {in_2[41]}]
set_input_transition -max 0.5  [get_ports {in_2[40]}]
set_input_transition -min 0.5  [get_ports {in_2[40]}]
set_input_transition -max 0.5  [get_ports {in_2[39]}]
set_input_transition -min 0.5  [get_ports {in_2[39]}]
set_input_transition -max 0.5  [get_ports {in_2[38]}]
set_input_transition -min 0.5  [get_ports {in_2[38]}]
set_input_transition -max 0.5  [get_ports {in_2[37]}]
set_input_transition -min 0.5  [get_ports {in_2[37]}]
set_input_transition -max 0.5  [get_ports {in_2[36]}]
set_input_transition -min 0.5  [get_ports {in_2[36]}]
set_input_transition -max 0.5  [get_ports {in_2[35]}]
set_input_transition -min 0.5  [get_ports {in_2[35]}]
set_input_transition -max 0.5  [get_ports {in_2[34]}]
set_input_transition -min 0.5  [get_ports {in_2[34]}]
set_input_transition -max 0.5  [get_ports {in_2[33]}]
set_input_transition -min 0.5  [get_ports {in_2[33]}]
set_input_transition -max 0.5  [get_ports {in_2[32]}]
set_input_transition -min 0.5  [get_ports {in_2[32]}]
set_input_transition -max 0.5  [get_ports {in_2[31]}]
set_input_transition -min 0.5  [get_ports {in_2[31]}]
set_input_transition -max 0.5  [get_ports {in_2[30]}]
set_input_transition -min 0.5  [get_ports {in_2[30]}]
set_input_transition -max 0.5  [get_ports {in_2[29]}]
set_input_transition -min 0.5  [get_ports {in_2[29]}]
set_input_transition -max 0.5  [get_ports {in_2[28]}]
set_input_transition -min 0.5  [get_ports {in_2[28]}]
set_input_transition -max 0.5  [get_ports {in_2[27]}]
set_input_transition -min 0.5  [get_ports {in_2[27]}]
set_input_transition -max 0.5  [get_ports {in_2[26]}]
set_input_transition -min 0.5  [get_ports {in_2[26]}]
set_input_transition -max 0.5  [get_ports {in_2[25]}]
set_input_transition -min 0.5  [get_ports {in_2[25]}]
set_input_transition -max 0.5  [get_ports {in_2[24]}]
set_input_transition -min 0.5  [get_ports {in_2[24]}]
set_input_transition -max 0.5  [get_ports {in_2[23]}]
set_input_transition -min 0.5  [get_ports {in_2[23]}]
set_input_transition -max 0.5  [get_ports {in_2[22]}]
set_input_transition -min 0.5  [get_ports {in_2[22]}]
set_input_transition -max 0.5  [get_ports {in_2[21]}]
set_input_transition -min 0.5  [get_ports {in_2[21]}]
set_input_transition -max 0.5  [get_ports {in_2[20]}]
set_input_transition -min 0.5  [get_ports {in_2[20]}]
set_input_transition -max 0.5  [get_ports {in_2[19]}]
set_input_transition -min 0.5  [get_ports {in_2[19]}]
set_input_transition -max 0.5  [get_ports {in_2[18]}]
set_input_transition -min 0.5  [get_ports {in_2[18]}]
set_input_transition -max 0.5  [get_ports {in_2[17]}]
set_input_transition -min 0.5  [get_ports {in_2[17]}]
set_input_transition -max 0.5  [get_ports {in_2[16]}]
set_input_transition -min 0.5  [get_ports {in_2[16]}]
set_input_transition -max 0.5  [get_ports {in_2[15]}]
set_input_transition -min 0.5  [get_ports {in_2[15]}]
set_input_transition -max 0.5  [get_ports {in_2[14]}]
set_input_transition -min 0.5  [get_ports {in_2[14]}]
set_input_transition -max 0.5  [get_ports {in_2[13]}]
set_input_transition -min 0.5  [get_ports {in_2[13]}]
set_input_transition -max 0.5  [get_ports {in_2[12]}]
set_input_transition -min 0.5  [get_ports {in_2[12]}]
set_input_transition -max 0.5  [get_ports {in_2[11]}]
set_input_transition -min 0.5  [get_ports {in_2[11]}]
set_input_transition -max 0.5  [get_ports {in_2[10]}]
set_input_transition -min 0.5  [get_ports {in_2[10]}]
set_input_transition -max 0.5  [get_ports {in_2[9]}]
set_input_transition -min 0.5  [get_ports {in_2[9]}]
set_input_transition -max 0.5  [get_ports {in_2[8]}]
set_input_transition -min 0.5  [get_ports {in_2[8]}]
set_input_transition -max 0.5  [get_ports {in_2[7]}]
set_input_transition -min 0.5  [get_ports {in_2[7]}]
set_input_transition -max 0.5  [get_ports {in_2[6]}]
set_input_transition -min 0.5  [get_ports {in_2[6]}]
set_input_transition -max 0.5  [get_ports {in_2[5]}]
set_input_transition -min 0.5  [get_ports {in_2[5]}]
set_input_transition -max 0.5  [get_ports {in_2[4]}]
set_input_transition -min 0.5  [get_ports {in_2[4]}]
set_input_transition -max 0.5  [get_ports {in_2[3]}]
set_input_transition -min 0.5  [get_ports {in_2[3]}]
set_input_transition -max 0.5  [get_ports {in_2[2]}]
set_input_transition -min 0.5  [get_ports {in_2[2]}]
set_input_transition -max 0.5  [get_ports {in_2[1]}]
set_input_transition -min 0.5  [get_ports {in_2[1]}]
set_input_transition -max 0.5  [get_ports {in_2[0]}]
set_input_transition -min 0.5  [get_ports {in_2[0]}]
set_input_transition -max 0.5  [get_ports {in_3[47]}]
set_input_transition -min 0.5  [get_ports {in_3[47]}]
set_input_transition -max 0.5  [get_ports {in_3[46]}]
set_input_transition -min 0.5  [get_ports {in_3[46]}]
set_input_transition -max 0.5  [get_ports {in_3[45]}]
set_input_transition -min 0.5  [get_ports {in_3[45]}]
set_input_transition -max 0.5  [get_ports {in_3[44]}]
set_input_transition -min 0.5  [get_ports {in_3[44]}]
set_input_transition -max 0.5  [get_ports {in_3[43]}]
set_input_transition -min 0.5  [get_ports {in_3[43]}]
set_input_transition -max 0.5  [get_ports {in_3[42]}]
set_input_transition -min 0.5  [get_ports {in_3[42]}]
set_input_transition -max 0.5  [get_ports {in_3[41]}]
set_input_transition -min 0.5  [get_ports {in_3[41]}]
set_input_transition -max 0.5  [get_ports {in_3[40]}]
set_input_transition -min 0.5  [get_ports {in_3[40]}]
set_input_transition -max 0.5  [get_ports {in_3[39]}]
set_input_transition -min 0.5  [get_ports {in_3[39]}]
set_input_transition -max 0.5  [get_ports {in_3[38]}]
set_input_transition -min 0.5  [get_ports {in_3[38]}]
set_input_transition -max 0.5  [get_ports {in_3[37]}]
set_input_transition -min 0.5  [get_ports {in_3[37]}]
set_input_transition -max 0.5  [get_ports {in_3[36]}]
set_input_transition -min 0.5  [get_ports {in_3[36]}]
set_input_transition -max 0.5  [get_ports {in_3[35]}]
set_input_transition -min 0.5  [get_ports {in_3[35]}]
set_input_transition -max 0.5  [get_ports {in_3[34]}]
set_input_transition -min 0.5  [get_ports {in_3[34]}]
set_input_transition -max 0.5  [get_ports {in_3[33]}]
set_input_transition -min 0.5  [get_ports {in_3[33]}]
set_input_transition -max 0.5  [get_ports {in_3[32]}]
set_input_transition -min 0.5  [get_ports {in_3[32]}]
set_input_transition -max 0.5  [get_ports {in_3[31]}]
set_input_transition -min 0.5  [get_ports {in_3[31]}]
set_input_transition -max 0.5  [get_ports {in_3[30]}]
set_input_transition -min 0.5  [get_ports {in_3[30]}]
set_input_transition -max 0.5  [get_ports {in_3[29]}]
set_input_transition -min 0.5  [get_ports {in_3[29]}]
set_input_transition -max 0.5  [get_ports {in_3[28]}]
set_input_transition -min 0.5  [get_ports {in_3[28]}]
set_input_transition -max 0.5  [get_ports {in_3[27]}]
set_input_transition -min 0.5  [get_ports {in_3[27]}]
set_input_transition -max 0.5  [get_ports {in_3[26]}]
set_input_transition -min 0.5  [get_ports {in_3[26]}]
set_input_transition -max 0.5  [get_ports {in_3[25]}]
set_input_transition -min 0.5  [get_ports {in_3[25]}]
set_input_transition -max 0.5  [get_ports {in_3[24]}]
set_input_transition -min 0.5  [get_ports {in_3[24]}]
set_input_transition -max 0.5  [get_ports {in_3[23]}]
set_input_transition -min 0.5  [get_ports {in_3[23]}]
set_input_transition -max 0.5  [get_ports {in_3[22]}]
set_input_transition -min 0.5  [get_ports {in_3[22]}]
set_input_transition -max 0.5  [get_ports {in_3[21]}]
set_input_transition -min 0.5  [get_ports {in_3[21]}]
set_input_transition -max 0.5  [get_ports {in_3[20]}]
set_input_transition -min 0.5  [get_ports {in_3[20]}]
set_input_transition -max 0.5  [get_ports {in_3[19]}]
set_input_transition -min 0.5  [get_ports {in_3[19]}]
set_input_transition -max 0.5  [get_ports {in_3[18]}]
set_input_transition -min 0.5  [get_ports {in_3[18]}]
set_input_transition -max 0.5  [get_ports {in_3[17]}]
set_input_transition -min 0.5  [get_ports {in_3[17]}]
set_input_transition -max 0.5  [get_ports {in_3[16]}]
set_input_transition -min 0.5  [get_ports {in_3[16]}]
set_input_transition -max 0.5  [get_ports {in_3[15]}]
set_input_transition -min 0.5  [get_ports {in_3[15]}]
set_input_transition -max 0.5  [get_ports {in_3[14]}]
set_input_transition -min 0.5  [get_ports {in_3[14]}]
set_input_transition -max 0.5  [get_ports {in_3[13]}]
set_input_transition -min 0.5  [get_ports {in_3[13]}]
set_input_transition -max 0.5  [get_ports {in_3[12]}]
set_input_transition -min 0.5  [get_ports {in_3[12]}]
set_input_transition -max 0.5  [get_ports {in_3[11]}]
set_input_transition -min 0.5  [get_ports {in_3[11]}]
set_input_transition -max 0.5  [get_ports {in_3[10]}]
set_input_transition -min 0.5  [get_ports {in_3[10]}]
set_input_transition -max 0.5  [get_ports {in_3[9]}]
set_input_transition -min 0.5  [get_ports {in_3[9]}]
set_input_transition -max 0.5  [get_ports {in_3[8]}]
set_input_transition -min 0.5  [get_ports {in_3[8]}]
set_input_transition -max 0.5  [get_ports {in_3[7]}]
set_input_transition -min 0.5  [get_ports {in_3[7]}]
set_input_transition -max 0.5  [get_ports {in_3[6]}]
set_input_transition -min 0.5  [get_ports {in_3[6]}]
set_input_transition -max 0.5  [get_ports {in_3[5]}]
set_input_transition -min 0.5  [get_ports {in_3[5]}]
set_input_transition -max 0.5  [get_ports {in_3[4]}]
set_input_transition -min 0.5  [get_ports {in_3[4]}]
set_input_transition -max 0.5  [get_ports {in_3[3]}]
set_input_transition -min 0.5  [get_ports {in_3[3]}]
set_input_transition -max 0.5  [get_ports {in_3[2]}]
set_input_transition -min 0.5  [get_ports {in_3[2]}]
set_input_transition -max 0.5  [get_ports {in_3[1]}]
set_input_transition -min 0.5  [get_ports {in_3[1]}]
set_input_transition -max 0.5  [get_ports {in_3[0]}]
set_input_transition -min 0.5  [get_ports {in_3[0]}]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
