#!/bin/bash

########################################################################
# Color Parameters
########################################################################
NO_COLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

CYCLE=$1
#if [ -z "$CYCLE" ]; then
#    echo -e "[Error] Please input your cycle time."
#    echo -e "Ex: ./00_tar 45"
#   exit 1
#fi

########################################################################
# TA Set Up Paremeter Here
########################################################################
LAB=Lab08
# DESIGN=huffman
ID=$(whoami)
# Copy Design Path 
ID_DIRECTORY="$LAB"_"$ID"
# FILELIST_FILE=../00_TESTBED/filelist.f
# DESIGN_FILE=../01_RTL/"$DESIGN".v
# MEM_FILE=../04_MEM
CYCLE_FILE="$CYCLE"_"$ID".txt
# Output Tar File Name
OUTPUT_FILE="$LAB"_"$ID".tar



########################################################################

# (0) Create Directory
if [ -d "$ID_DIRECTORY" ]; then
    echo "[Info] Directory exists, Remove old directory and creat new one."
	rm -rf $ID_DIRECTORY
    mkdir "$ID_DIRECTORY"
else
    mkdir "$ID_DIRECTORY"
    echo "[Info] Directory created."
fi

# (1) Copy File List File
# cp "$FILELIST_FILE" ./"$ID_DIRECTORY"/filelist_"$ID".f 
# echo -e "[Info] $FILELIST_FILE has been copied."
# (2) Copy Design File
# cp "$DESIGN_FILE" ./"$ID_DIRECTORY"/"$DESIGN"_"$ID".v  
# echo -e "[Info] $DESIGN_FILE has been copied."
# (3) Create Cycle Time
# touch ./"$ID_DIRECTORY"/"$CYCLE_FILE"
# echo -e "[Info] $CYCLE_FILE has been copied."
# (4) Copy SystemC Desgin File
DESIGN=sort
DESIGN_FILE=../../1_SystemC/"$DESIGN".h
cp "$DESIGN_FILE" ./"$ID_DIRECTORY"/"$DESIGN"_"$ID".h  
echo -e "[Info] $DESIGN_FILE has been copied."

DESIGN=sort
DESIGN_FILE=../../1_SystemC/"$DESIGN".cpp
cp "$DESIGN_FILE" ./"$ID_DIRECTORY"/"$DESIGN"_"$ID".cpp 
echo -e "[Info] $DESIGN_FILE has been copied."

# (5) tar
echo -e "[Info] Now start tar zcvf "$ID_DIRECTORY".tar.gz "
tar zcvf "$ID_DIRECTORY".tar.gz "$ID_DIRECTORY" 
echo -e "[Success] "$ID_DIRECTORY".tar.gz Sucessfully."
########################################################################