#!/bin/bash

########################################################################
# Color Parameters
########################################################################
NO_COLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

########################################################################
# TA Set Up Paremeter Here
########################################################################
DEADLINE_1DE="2024/05/13 08:00:00"
# DEADLINE_2DE="2025/04/02 23:59:59"
# DEADLINE_3DE="2023/01/31 12:00:00"
ID=$(whoami)
LAB=Lab08
SUBMIT_TAR_FILE="$LAB"_"$ID".tar.gz
FILESYSTEM=~DCSTA03

########################################################################
# (1) Check Submit time is over or not
########################################################################

# Date formating
date_now_num=$(date  +"%Y%m%d%H%M%S")
date_now_write_date=$(date  +"%Y/%m/%d")
date_now_write_time=$(date  +"%H:%M:%S")

# 1st demo
due_date_num_1=$(date -d "$DEADLINE_1DE" +"%Y%m%d%H%M%S")
due_date_dis_1=$(date -d "$DEADLINE_1DE")
# 2nd demo
# due_date_num_2=$(date -d "$DEADLINE_2DE" +"%Y%m%d%H%M%S")
# due_date_dis_2=$(date -d "$DEADLINE_2DE")
# 3rd demo
# due_date_num_3=$(date -d "$DEADLINE_3DE" +"%Y%m%d%H%M%S")
# due_date_dis_3=$(date -d "$DEADLINE_3DE")

# Flow
if [ $due_date_num_1 -ge $date_now_num ]; then
    demo=demo
# elif [ $due_date_num_2 -ge $date_now_num ]; then
#    demo=after-class
# elif [ $due_date_num_3 -ge $date_now_num ]; then
#     demo=3rd_demo
else 
    echo -e "[Error] Your submission is fail. Please check out report."
    echo -e "\n"
    echo -e "========================================================"
    echo -e "                    Submit Report                       "
    echo -e "========================================================"
    echo -e "Result          : $RED"" Late submission $NO_COLOR"
    echo -e "The demo deadline  : $YELLOW $due_date_dis_1 $NO_COLOR"
    echo -e "Your submission time   : $RED $date_now_num $NO_COLOR"
    echo -e "========================================================"
    echo -e "        ----------------------------               "
    echo -e "        --                        --       |\__||  "
    echo -e "        --  OOPS!!                --      / X,X  | "
    echo -e "        --                        --    /_____   | "
    echo -e "        --  \033[0;31mSubmission Failed!!\033[m   --   /^ ^ ^ \\  |"
    echo -e "        --                        --  |^ ^ ^ ^ |w| "
    echo -e "        ----------------------------   \\m___m__|_|"
    echo -e "========================================================"
    echo -e "\n"
    exit 1
fi
echo -e "[Info] Deadline check OK ..."

########################################################################
# (2) Check submit file
########################################################################

if [ ! -f $SUBMIT_TAR_FILE ]; then
    echo -e "[Error] Your submission is fail. Please check out report."
    echo -e "\n"
    echo -e "========================================================"
    echo -e "                    Submit Report                       "
    echo -e "========================================================"
    echo -e "Result: $RED"" No $SUBMIT_TAR_FILE is found in this directory $NO_COLOR"
    echo -e "$YELLOW""Files in this folder: $NO_COLOR"
    ls
    echo -e "========================================================"
    echo -e "        ----------------------------               "
    echo -e "        --                        --       |\__||  "
    echo -e "        --  OOPS!!                --      / X,X  | "
    echo -e "        --                        --    /_____   | "
    echo -e "        --  \033[0;31mSubmission Failed!!\033[m   --   /^ ^ ^ \\  |"
    echo -e "        --                        --  |^ ^ ^ ^ |w| "
    echo -e "        ----------------------------   \\m___m__|_|"
    echo -e "========================================================"
    echo -e "\n"
    exit 1
fi
echo -e "[Info] File check OK ..."

# demo in student folder
# tcsh_command='source /RAID2/cad/synopsys/CIC/pa_virtualizer.cshrc'

# Execute the tcsh command using tcsh interpreter
# tcsh -c "$tcsh_command"

python3 ~DCSTA03/Lab08_submit_script/demo_lab08.py $ID $LAB $date_now_write_date $date_now_write_time
# python3 demo_hw3.py $ID $LAB $date_now_write_date $date_now_write_time


########################################################################
# (3) Comfirm submit file
########################################################################
target_file="$FILESYSTEM"/"$LAB"/"code"/"$LAB"_"$ID".tar.gz
target_result_file="$FILESYSTEM"/"$LAB"/"$demo"/DEMO_RESULT_"$ID".csv

#echo $target_file
#Flow 
echo -e "[Info] Your file will be submitted to: $LIGHTCYAN $demo $NO_COLOR"
if [ -f $target_file ]; then
    echo -e "[Warning] $YELLOW $demo has been submitted. $NO_COLOR"
    echo -e "[Warning] $YELLOW It will overwrite your original file. $NO_COLOR"
    
fi
read -p "[Info] Are you sure you want to submit your design file?(y/n):" ans
if [ -z "$ans" ]; then
    echo -e "[Error] Wrong answer, submission aborted."
    exit 1
fi
if  [ $ans != n ] && [ $ans != N ] && [ $ans != Y ] && [ $ans != y ]; then
    echo -e "[Error] Wrong answer, submission aborted."
    exit 1
fi
if [ $ans == n ] || [ $ans == N ]; then
    echo -e "[Info] Submission aborted without uploading."
    exit 1
fi

echo -e "[Info] Now submit $SUBMIT_TAR_FILE file to system."
rm -rf $target_file
cp $SUBMIT_TAR_FILE $target_file
cp ../DEMO_RESULT.csv DEMO_RESULT_"$ID".csv
cp DEMO_RESULT_"$ID".csv $target_result_file
chmod 640 $target_file
echo -e "[Success] Copying Sucessfully."
echo -e "========================================================"
echo -e "                    Submit Report                       "
echo -e "========================================================"
echo -e "Result          : $CYAN $demo $source_file has been submitted. $NO_COLOR"
echo -e "Submission time : $CYAN $date_now_write_date $date_now_write_time $NO_COLOR"
echo -e "========================================================"
echo -e "        ----------------------------               "
echo -e "        --                        --       |\__||  "
echo -e "        --  Congratulations !!    --      / O.O  | "
echo -e "        --                        --    /_____   | "
echo -e "        --  \033[0;32m\e[05mSubmission Sucessful!!\033[m--   /^ ^ ^ \\  |"
echo -e "        --                        --  |^ ^ ^ ^ |w| "
echo -e "        ----------------------------   \\m___m__|_|"
echo -e "   \033[0;31m\e[05mPlease remember to check your submission with ./02_check !! \033[m"
echo -e "   \033[0;31m\e[05mPlease remember to check your submission with ./02_check !! \033[m"
echo -e "   \033[0;31m\e[05mPlease remember to check your submission with ./02_check !! \033[m"
echo -e "========================================================"
