#!/bin/bash
# This file was generated by SystemC Shell to start a co-simulation outside of SystemC Shell

#set -x
if [ -n "$1" ] ; then
  echo "$@" >.cosim_command_args
fi
touch .cosim_command_args
export CWR_COSIM_ARGS_FILENAME=.cosim_command_args
export CWR_HDL_SIMULATOR=vcs
export CWR_SCSIM_PREFIX=no_prefix
unset CWR_COSIM_DELTA_CYCLE_SYNC
export CWR_HDL_VERILOG_TIMESCALE=ps
export CWR_HDL_STRUCTURAL_OPTIMIZATION=on
export CWR_HDL_MODULE_NAMES=/RAID2/COURSE/DCS/DCS111/Lab07/pa/export/Debug/ConvergenSC/cosim/hdl_module_names
export CWR_SYSCSIMULATOR=Debug/sim.so
export INCA_64BIT=1
export VCS_TARGET_ARCH=amd64
export MTI_VCO_MODE=64
Debug/make -f /RAID2/COURSE/DCS/DCS111/Lab07/pa/export/Debug/ConvergenSC/cosim/Makefile.cosim build
if [ $? -ne 0 ] ; then
  echo "Build failed."
  return 1
fi
export CWR_COSIM_BATCH=true
Debug/make -f /RAID2/COURSE/DCS/DCS111/Lab07/pa/export/Debug/ConvergenSC/cosim/Makefile.cosim runbatch
rm -f .cosim_command_args
